Add program directories to JELLYFIN_ARGS for sysvinit compatibility
jellyfin/jellyfin pull request #10039
Opened 2023-07-24 00:15 UTC by hugueslarrive

start-stop-daemon does not pass the environment variables *_DIR to jellyfin which fails to launch.
**Changes**

Add program directories to JELLYFIN_ARGS in /etc/default/jellyfin
**Issues**

Fixes #10037

2023-07-24 15:27 UTC, hankster112 commented
Is `$JELLFIN_ADDITIONAL_OPTS` supposed to be `$JELLYFIN_ADDITIONAL_OPTS`? It was missing a Y.

2023-07-24 21:18 UTC, hankster112 requested changes
Change `$JELLFIN_ADDITIONAL_OPTS` to `$JELLYFIN_ADDITIONAL_OPTS" to fix typo.

2023-08-10 09:31 UTC, Shadowghost approved these changes

2023-09-12 09:09 UTC, Bond-009 approved these changes

2023-09-12 09:10 UTC, merged