Combined Title and Overview for multi-episodes files for NFO file
jellyfin/jellyfin pull request #10080
Opened 2023-08-04 15:41 UTC by scampower3

Now multi-episodes file show all episodes titles and overviews instead of only just the first episode's title and overview.

**Changes**

- Iterates through each episodedetails block. Grabs the title and plot and concats them together with a " / " delimiting each other.

**Issues**
Partially fixes #2980

2023-08-14 09:58 UTC, Shadowghost approved these changes

2023-09-11 12:02 UTC, Bond-009 requested changes

2023-09-11 12:02 UTC, Bond-009 commented on MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
> +                                        name.Append(" / " + reader.ReadElementContentAsString());
```suggestion
                                        name.Append(" / ").Append(reader.ReadElementContentAsString());
```

2023-09-11 12:02 UTC, Bond-009 commented on MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
> +                                        overview.Append(" / " + reader.ReadElementContentAsString());
```suggestion
                                        overview.Append(" / ").Append(reader.ReadElementContentAsString());
```

2023-09-15 18:41 UTC, JPVenson commented on MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
> +                        while (!reader.EOF && reader.ReadState == ReadState.Interactive)
Would extract into own method

2023-09-15 18:42 UTC, JPVenson requested changes

2023-09-15 18:42 UTC, JPVenson commented on MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs
> +                        while (!reader.EOF && reader.ReadState == ReadState.Interactive)
Would extract into own method

2023-10-02 15:32 UTC, barronpm approved these changes

2023-10-08 15:01 UTC, Bond-009 approved these changes

2023-10-10 11:12 UTC, merged