Extend collections cleanup task to include playlists too
jellyfin/jellyfin pull request #10234
Opened 2023-09-16 13:11 UTC by Shadowghost

Playlists have the same issue as collections with items not being removed from them when they are removed.

**Changes**
* Extend collection cleanup task to clean up playlists too.

**Issues**
Partially addresses #10216

2023-09-16 14:37 UTC, crobibero commented
ci is failing with 
```
/home/vsts/work/1/s/Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs(112,90): error SA1127: Generic type constraints should be on their own line 
```

2023-09-16 14:38 UTC, crobibero commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +            _logger.LogDebug("There is no collection folder to be found");
```suggestion
            _logger.LogDebug("There is no playlists folder to be found");
```

2023-09-16 14:38 UTC, crobibero commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +        _logger.LogDebug("Found {PlaylistLength} boxsets", playlists.Length);
```suggestion
        _logger.LogDebug("Found {PlaylistLength} playlists", playlists.Length);
```

2023-09-16 15:30 UTC, crobibero approved these changes

2023-09-17 11:53 UTC, Bond-009 requested changes

2023-09-17 11:53 UTC, Bond-009 commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +        if (itemsToRemove.Count != 0)
```suggestion
        List<LinkedChild> itemsToRemove = null;
        foreach (var linkedChild in folder.LinkedChildren)
        {
            if (!File.Exists(folder.Path))
            {
                _logger.LogInformation("Item in {FolderName} cannot be found at {ItemPath}", folder.Name, linkedChild.Path);
                (itemsToRemove ??= new List<LinkedChild>()).Add(linkedChild);
            }
        }

        if (itemsToRemove is not null)
```

2023-09-17 11:53 UTC, Bond-009 commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +            itemsToRemove.Clear();
```suggestion
```

2023-09-17 12:38 UTC, Bond-009 commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +        List<LinkedChild> itemsToRemove = null;
```suggestion
        List<LinkedChild>? itemsToRemove = null;
```
Should fix build error

2023-09-17 14:53 UTC, Bond-009 commented on Emby.Server.Implementations/ScheduledTasks/Tasks/CleanupCollectionAndPlaylistPathsTask.cs
> +
```suggestion
```
Should be the last issue

2023-09-18 11:09 UTC, JPVenson approved these changes

2023-09-19 11:41 UTC, Bond-009 approved these changes

2023-09-22 12:55 UTC, merged