feat: add EnableMetrics override with environment variable
jellyfin/jellyfin pull request #10503
Opened 2023-10-31 16:51 UTC by yohanb

**Changes**
Adds the ability to override the `EnableMetrics` configuration value from the `system.xml` files.  The configuration value is added to the ASP.NET config framework so it can also be set through the other config sources (`appsettings.json`, etc.),

**Issues**
[Fixes issue 6247](https://github.com/jellyfin/jellyfin/issues/6247)

2023-11-15 15:51 UTC, yohanb commented
anyone from the Jellyfin maintainers gonna chime in?

2023-11-23 21:54 UTC, cvium commented on Emby.Server.Implementations/ApplicationHost.cs
> +        public bool EnableMetrics => ConfigurationManager.Configuration.EnableMetrics || this._startupConfig.GetValue<bool>(EnableMetricsKey);
Two things:

1. We don't use `this`
2. One should take priority over the other (probably the env var). With this expression, both must either not be set or be false to disable it.

2023-11-24 09:17 UTC, JPVenson requested changes

2023-11-24 09:17 UTC, JPVenson commented on Emby.Server.Implementations/ApplicationHost.cs
> +        public bool EnableMetrics => ConfigurationManager.Configuration.EnableMetrics || this._startupConfig.GetValue<bool>(EnableMetricsKey);
Also i dont like the location of this property. FeatureFlags should not be aggregated in the Host class. Why not keep it in the ConfigManager and extend the check there?

2026-05-06 09:52 UTC, JPVenson commented
closed due to inactivity

2026-05-06 09:52 UTC, closed without merging