Add --output-dir argument to `build.sh`
jellyfin/jellyfin pull request #10673
Opened 2023-12-03 21:24 UTC by Erotemic

Currently the build script running in native mode will write the output to "../bin" with respect to the CWD, which is where jellyfin is cloned to. I keep all of my code repos in the same folder, so I don't want jellyfin to write to the folder above it. At the same time I don't want to break existing default behavior. Thus, I've added the option `--output-dir`, which lets the user specify the prefix where "bin/<platform>/..." outputs are written to.

I've added the appropriate help docs. Other than that, the change is straightforward. 

**Changes**
Add `-o / --output-dir` argument to `build.sh`

2023-12-18 20:24 UTC, joshuaboniface requested changes

2023-12-18 20:24 UTC, joshuaboniface commented on build.sh
> +if [[ "$OUTPUT_DIR" == "" ]]; then
Use `[[ -z ${OUTPUT_DIR} ]]; then` here instead.

2023-12-18 22:10 UTC, Erotemic commented on build.sh
> +if [[ "$OUTPUT_DIR" == "" ]]; then
```suggestion
if [[ -z "${OUTPUT_DIR}" ]]; then
```

2023-12-18 22:10 UTC, Erotemic commented on build.sh
> +if [[ "$OUTPUT_DIR" == "" ]]; then
Done

2024-03-18 14:45 UTC, Gauvino commented
Can be closed due to https://github.com/jellyfin/jellyfin/pull/11162

2024-03-18 14:52 UTC, closed without merging