Use `eof_action=pass` when overlaying subtitles
jellyfin/jellyfin pull request #10710
Opened 2023-12-12 01:51 UTC by jkhsjdhjs

The previous behavior using `eof_action=endall` and `shortest=1` would end the video stream if one of the input stream (video, subtitle) ends. In some cases the duration of the overlayed subtitles is shorter than the video stream, causing the output to end when the subtitles end and dropping the remaining video stream.

This commit changes this behavior so `eof_action=pass` is used instead, which continues passing the video stream through even if the subtitles end earlier [1]. `shortest=1` is also removed, as this option implies `eof_action=endall`.

If the subtitle stream has a higher duration than the video stream, the output will also end with the video stream without `shortest=1`, as the video stream is the primary input to the `overlay` filter.

Fix #10698

[1] https://ffmpeg.org/ffmpeg-filters.html#Options-for-filters-with-several-inputs-_0028framesync_0029

2023-12-12 12:48 UTC, Bond-009 approved these changes

2023-12-12 13:02 UTC, nyanmisaka requested changes
`overlay_vulkan` should also apply the same change.

https://github.com/jellyfin/jellyfin/blob/82527314c1e92cce1bcf38140bbab3f99beea560/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L4619

2023-12-12 22:43 UTC, jkhsjdhjs commented
> `overlay_vulkan` should also apply the same change.
> 
> https://github.com/jellyfin/jellyfin/blob/82527314c1e92cce1bcf38140bbab3f99beea560/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L4619

Good catch! I initially did the change on the `release-10.8.z` branch, which doesn't have the `overlay_vulkan` line. I just fixed it.

2023-12-13 08:29 UTC, nyanmisaka commented
> Good catch! I initially did the change on the `release-10.8.z` branch, which doesn't have the `overlay_vulkan` line. I just fixed it.

Found another one. Please remove the `:shortest=1` in this line.
https://github.com/jellyfin/jellyfin/blob/bcc376a3520dadd43b67f869cac9ede368368b1f/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L4459

2023-12-13 12:13 UTC, jkhsjdhjs commented
> Found another one. Please remove the `:shortest=1` in this line.
> 
> https://github.com/jellyfin/jellyfin/blob/bcc376a3520dadd43b67f869cac9ede368368b1f/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L4459

Done. I found two other occurances of the same line and removed the `shortest=1` there as well.

2023-12-13 12:27 UTC, nyanmisaka approved these changes

2023-12-13 12:50 UTC, cvium approved these changes

2023-12-13 12:50 UTC, merged