Added logging for where config logs and cache directories are stored
jellyfin/jellyfin pull request #11124
Opened 2024-03-08 15:37 UTC by PeachesMLG

Added logging for where config logs and cache directories are stored

**Changes**
Took me a while to figure out where the config directory was, so I thought some logging for this might help any future people having the same issue

**Issues**
N/A

2024-03-09 12:00 UTC, JPVenson commented
FYI those paths are also shown in the Dashboard WebUI

![image](https://github.com/jellyfin/jellyfin/assets/6794763/3e26c8e4-4f0b-43bd-a4ed-8a0a3e59ff6a)

2024-03-09 12:02 UTC, JPVenson commented
Also, the Cache path should already be printed in the log by the BaseConfigurationManager

2024-03-09 20:16 UTC, Bond-009 requested changes

2024-03-09 20:16 UTC, Bond-009 commented on Jellyfin.Server/Helpers/StartupHelpers.cs
> +        logger.LogInformation("Cache Path: {CachePath}", appPaths.CachePath);
```suggestion
        logger.LogInformation("Log directory path: {LogDirectoryPath}", appPaths.LogDirectoryPath);
        logger.LogInformation("Config directory path: {ConfigurationDirectoryPath}", appPaths.ConfigurationDirectoryPath);
        logger.LogInformation("Cache path: {CachePath}", appPaths.CachePath);
```
Consistent with the other log lines

2024-03-09 21:28 UTC, PeachesMLG commented
> FYI those paths are also shown in the Dashboard WebUI
> 
> ![image](https://private-user-images.githubusercontent.com/6794763/311435858-3e26c8e4-4f0b-43bd-a4ed-8a0a3e59ff6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTk5NjIsIm5iZiI6MTcxMDAxOTY2MiwicGF0aCI6Ii82Nzk0NzYzLzMxMTQzNTg1OC0zZTI2YzhlNC00ZjBiLTQzYmQtYTRlZC04YTBhM2U1OWZmNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMjEyNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU4Y2M1ZjU1ODUzM2QwZjdjNGI1NTY0OWY5OTBmZTQ1ZGY5ZTE5YWY5YjQxYWJkYzlmMTg3ODY4YjFlZTAwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gx2ku4ZrS9uzlc00BqIsTSvAI2YOOY73rnAc-tk8ZfQ)

Thats good to know actually, thanks

2024-03-09 22:28 UTC, crobibero approved these changes

2024-03-11 17:41 UTC, Bond-009 approved these changes

2024-03-11 17:41 UTC, merged