Bugfix/fix permission check on trickplay
jellyfin/jellyfin pull request #11167
Opened 2024-03-16 12:02 UTC by JPVenson

**Changes**
 - Fixed Trickplay api not checking for Visibility for requested items

**Issues**
Fixes #11166

2024-03-16 12:50 UTC, Shadowghost approved these changes

2024-03-16 13:30 UTC, nielsvanvelzen requested changes

2024-03-16 13:30 UTC, nielsvanvelzen commented on Jellyfin.Api/Controllers/TrickplayController.cs
> +    /// <response code="400">Requested item not found.</response>
This should be 404

2024-04-14 14:19 UTC, crobibero commented
https://github.com/jellyfin/jellyfin/pull/11171

2024-04-14 14:19 UTC, closed without merging