Don't expect `BaseItem` to be a movie/video file.
jellyfin/jellyfin pull request #11204
Opened 2024-03-24 00:13 UTC by revam

**Changes**

This fix is mainly so I can mass-add series _and_ movie entries using a `IMultiItemResolver` without having to resort to complicated logic using _both_ a `IItemResolver` and a `IMultiItemResolver` by splitting up what gets added where.

I've also added three new interface methods to the `IDirectoryService`, one of which is used in the modified
`ResolverHelper.SetInitialItemValues(…)` to get the file system entry info for the item regardless of which type the file system entry is.

In my local testing so far I haven't found any issues introduced by this change.

**Issues**

2024-03-24 01:45 UTC, revam commented
Also it should be noted that if I were to do the workaround of using both a `IMultiItemResolver` and `IItemResolver` then it will fail to properly create the Show/Series entries for media libraries without a collection type when the collection doesn't contain any movies (yet), because of how the built-in resolving logic and how the built-in movie resolver works, in addition to how we need to defer the creation of shows/series onto the next set of single item resolvers because the `Items` field on the `MultiItemResolverResult` contains an empty array (because we don't have any movies added to the collection yet) and thus the internals will skip the `ExtraFiles` even if they're set because the `Items` is empty, and move on to the built-in movie resolver which will mark all the files within the folders as movies and it won't ever reach the single item resolvers.

But with this code in place I can place my resolver before the movie resolver and add both the series and movies at once without any issues.

2024-03-24 01:49 UTC, Gauvino commented
Failing build action with your change

2024-03-24 06:42 UTC, revam commented
I fixed up the tests that were failing and added two new tests for directories.

2024-06-11 05:30 UTC, nielsvanvelzen approved these changes

2024-06-11 16:57 UTC, Shadowghost approved these changes

2024-06-15 15:44 UTC, Bond-009 requested changes

2024-06-15 15:44 UTC, Bond-009 commented on MediaBrowser.Controller/Providers/DirectoryService.cs
> +            return entry != null && entry.IsDirectory ? entry : null;
```suggestion
            return entry is not null && !entry.IsDirectory ? entry : null;
        }

        public FileSystemMetadata? GetDirectory(string path)
        {
            var entry = GetFileSystemEntry(path);
            return entry is not null && entry.IsDirectory ? entry : null;
```

2024-06-15 17:51 UTC, Bond-009 approved these changes

2024-06-20 13:02 UTC, crobibero approved these changes

2024-06-27 07:45 UTC, merged