add otel
jellyfin/jellyfin pull request #11386
Opened 2024-04-18 21:21 UTC by lackolaxton

Add OTEL exporter options. For anyone that self hosts and has a collector, it would be useful for thme to get the metrics and tracing to help monitor performance.

2024-04-19 19:03 UTC, rasmustwh commented
Wouldn't auto-instrumentation be more useful and flexible for everyone? The hardcoded instrumentation seems rather overkill for the most use cases.

2024-04-19 20:54 UTC, lackolaxton commented
> Wouldn't auto-instrumentation be more useful and flexible for everyone? The hardcoded instrumentation seems rather overkill for most use cases.

Never really thought of auto instrumentation. If someone is hosting in containers though it'll make it hard to do, so having this option at least gives the Hoster a way to get decent metrics etc.

I plan to try and add some tracing and better metrics so this is just a start

2024-07-17 14:46 UTC, crobibero requested changes
if any of the properties are improperly specified it will cause the server to fail to start- I think we should just log the exception and continue.

2024-07-17 14:46 UTC, crobibero commented on MediaBrowser.Model/Configuration/OtelConfiguration.cs
> +    public string Meters { get; set; } = string.Empty;
Looks like this should be an array

2024-07-17 14:46 UTC, crobibero commented on MediaBrowser.Model/Configuration/OtelConfiguration.cs
> +    public string ActivitySources { get; set; } = string.Empty;
Looks like this should be an array

2024-07-17 14:46 UTC, crobibero commented on Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
> +                        .AddHttpClientInstrumentation();
```suggestion
                            .AddMeter(config.Meters)
                            .AddAspNetCoreInstrumentation()
                            .AddRuntimeInstrumentation()
                            .AddHttpClientInstrumentation();
```

2024-07-17 14:46 UTC, crobibero commented on Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
> +                        .AddHttpClientInstrumentation();
```suggestion
                            .AddSource(config.ActivitySources)
                            .AddAspNetCoreInstrumentation()
                            .AddHttpClientInstrumentation();
```

2024-07-17 14:46 UTC, crobibero commented on Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs
> +                    .ConfigureResource(resourceBuilder => resourceBuilder.AddService("JellyFin", appVersion))
```suggestion
                    .ConfigureResource(resourceBuilder => resourceBuilder.AddService("Jellyfin", appVersion))
```

2024-09-18 20:18 UTC, closed without merging