feat: add audio remux to UniversalAudioController
jellyfin/jellyfin pull request #11399
Opened 2024-04-21 22:46 UTC by gnattu

**Changes**

This PR adds audio remuxing (copying audio into another container without transcoding) support to the UniversalAudioController, allowing the client to request the audio to be in a specific container. When remuxing with HLS, the HLS container's constraint applies, and it will fallback to transcoding when the original audio codec is not supported by the chosen HLS container. When remuxing with HTTP, this assumes that the client-provided container supports the audio codec. If it does not, ffmpeg would fail.

This would allow clients with strict container requirements to playback certain audio codecs. For example, Opus on Safari can be played with HLS + fmp4.

This can also workarounds a lot of container related issues, as listed below in the issues section.

**Issues**

#11113 Tis one is due to the flac/mp3 container containing too little information, the client's estimation of the "ticks" might not be accurate enough. Allowing the client to force an HLS remuxing with fmp4 can mitigate this issue as the mp4 container has more information about the timing.

#3731 This issue arises because the flac container has non-standard metadata tags, causing the client to refuse to play the file. This can be mitigated by falling back to HLS remuxing when direct play fails, or simply by forcing HLS remuxing anyway.

2024-07-17 18:19 UTC, nyanmisaka approved these changes

2024-07-18 09:36 UTC, Bond-009 requested changes

2024-07-18 09:36 UTC, Bond-009 commented on Jellyfin.Api/Controllers/UniversalAudioController.cs
> +            var requestedSegmentContainer = Array.Exists(supportedHlsContainers, element => element == transcodingContainer) ? transcodingContainer : "ts";
```suggestion
            var requestedSegmentContainer = Array.Exists(
                supportedHlsContainers, 
                element => string.Equals(element, transcodingContainer, StringComparison.OrdinalIgnoreCase)) ? transcodingContainer : "ts";
```

2024-07-18 09:36 UTC, Bond-009 commented on Jellyfin.Api/Controllers/UniversalAudioController.cs
> +            var segmentContainer = Array.Exists(supportedHlsContainers, element => element == mediaSource.TranscodingContainer) ? mediaSource.TranscodingContainer : requestedSegmentContainer;
```suggestion
            var segmentContainer = Array.Exists(
                supportedHlsContainers,
                element => string.Equals(element, mediaSource.TranscodingContainer, StringComparison.OrdinalIgnoreCase)) ? mediaSource.TranscodingContainer : requestedSegmentContainer;
```

2024-07-18 09:36 UTC, Bond-009 commented on MediaBrowser.Model/Dlna/StreamBuilder.cs
> +                remuxContainer = Array.Exists(supportedHlsContainers, element => element == directPlayInfo.Profile?.Container) ? directPlayInfo.Profile?.Container : remuxContainer;
```suggestion
                remuxContainer = Array.Exists(supportedHlsContainers, element => string.Equals(element, directPlayInfo.Profile?.Container, StringComparison.OrdinalIgnoreCase)) ? directPlayInfo.Profile?.Container : remuxContainer;
```

2024-07-18 10:18 UTC, Bond-009 approved these changes

2024-07-18 12:12 UTC, merged