Enable nullable for DtoService and DtoOptions
jellyfin/jellyfin pull request #11432
Opened 2024-04-25 10:42 UTC by Bond-009

2024-04-25 15:17 UTC, Shadowghost approved these changes

2024-05-05 16:51 UTC, MarkCiliaVincenti approved these changes

2024-07-29 16:18 UTC, crobibero approved these changes

2024-07-29 19:50 UTC, nielsvanvelzen requested changes
Doesn't compile

```
 Error: /home/runner/work/jellyfin/jellyfin/Jellyfin.Api/Controllers/LiveTvController.cs(691,52): error CS8601: Possible null reference assignment. [/home/runner/work/jellyfin/jellyfin/Jellyfin.Api/Jellyfin.Api.csproj]
```

2024-07-29 20:04 UTC, nielsvanvelzen approved these changes

2024-07-29 20:19 UTC, merged