Fix absolute path checking on windows
jellyfin/jellyfin pull request #11570
Opened 2024-05-12 16:08 UTC by gnattu

The fragile path matching no longer works with dotnet 8, causing Windows users to lose collection items because the item path is incorrectly validated, then the server will remove all items due to file not found.

**Changes**

**Issues**

See forum https://forum.jellyfin.org/t-items-in-collections-all-gone-after-10-9-0-upgrade?pid=22471#pid22471

2024-05-12 17:49 UTC, crobibero commented
Should add tests for these cases

2024-05-12 17:59 UTC, Shadowghost approved these changes

2024-05-12 18:21 UTC, Bond-009 requested changes

2024-05-12 18:21 UTC, Bond-009 commented on tests/Jellyfin.Server.Implementations.Tests/IO/ManagedFileSystemTests.cs
> +        [Theory]
Use `SkippableTheoryAttribute`

See `GetFileInfo_DanglingSymlink_ExistsFalse` test below on how it's used

2024-05-12 19:13 UTC, Bond-009 approved these changes

2024-05-12 19:47 UTC, crobibero approved these changes

2024-05-12 20:08 UTC, nielsvanvelzen approved these changes

2024-05-12 21:12 UTC, merged

2024-05-15 18:28 UTC, zotabee commented
Thank you so much!!!

Collections are back, without restoring a backup. Great job!