Fix series status parsing
jellyfin/jellyfin pull request #11648
Opened 2024-05-14 23:27 UTC by Shadowghost

NFOs can include more than our three status descriptions: https://www.themoviedb.org/bible/tv

**Changes**
* Add helper function to properly transform different strings into our enum values

2024-05-15 03:28 UTC, crobibero commented on Emby.Naming/TV/TvParserHelpers.cs
> +        switch (status)
switch is case-sensitive, should probably do case-insensitive matching here

2024-05-15 19:58 UTC, Bond-009 requested changes

2024-05-15 19:58 UTC, Bond-009 commented on Emby.Naming/TV/TvParserHelpers.cs
> +    private static readonly List<string> _endedState = ["Cancelled"];
Use arrays instead of lists

2024-05-15 21:52 UTC, Bond-009 approved these changes

2024-05-15 21:52 UTC, Bond-009 commented on tests/Jellyfin.Naming.Tests/TV/TvParserHelpersTest.cs
> +namespace Jellyfin.Naming.Tests.TV
Use file scope namespaces for new files

2024-05-15 21:52 UTC, Bond-009 commented on tests/Jellyfin.Naming.Tests/TV/TvParserHelpersTest.cs
> +            Assert.Equal(success, successful);
I prefer separate tests for valid and invalid inputs, it reduces the complexity of the test function and reduces arguments

2024-05-15 23:22 UTC, crobibero approved these changes

2024-05-16 07:53 UTC, Bond-009 approved these changes

2024-05-16 17:06 UTC, merged