Trim leading and trailing whitespace from item search term.
jellyfin/jellyfin pull request #11896
Opened 2024-05-31 16:31 UTC by riashg

**Changes**
Trim the leading and trailing whitespace from the searchTerm used in the ItemsController GetItems() method.

**Issues**
Fixes #11868

2024-05-31 17:00 UTC, gnattu commented
I think this should be implemented by clients and not to put it on the server like this.

2024-09-03 14:36 UTC, JPVenson commented
> I think this should be implemented by clients and not to put it on the server like this.

I dont think it hurts to do it on the server to keep a more generalised resultset. It costs next to nothing and only helps because if some client forgets it we have it covered.

2024-09-03 14:37 UTC, JPVenson approved these changes

2024-09-04 19:10 UTC, crobibero requested changes
I think a proper place to make this change would be in `SqliteItemRepository` in the `BindSearchParams` function.

2026-02-10 16:24 UTC, theguymadmax commented
This issue has been resolved: #14879

2026-02-10 16:24 UTC, closed without merging