Remove empty image folders recursively
jellyfin/jellyfin pull request #12025
Opened 2024-06-07 20:14 UTC by Shadowghost

Seems like we can have nested folders, so cehck recursively before removing.

**Changes**
* Recursively check for files and remove the folder recursively if none are found

**Issues**
Fixes #12023 (potentially)

2024-06-20 13:10 UTC, crobibero approved these changes

2024-06-23 15:54 UTC, Bond-009 requested changes

2024-06-23 15:54 UTC, Bond-009 commented on MediaBrowser.Providers/Manager/ItemImageProvider.cs
> +                var localImages = images.Where(i => i.Path.StartsWith(oldLocalMetadataDirectory, StringComparison.Ordinal)).ToList();
This is unused?

2024-06-24 11:30 UTC, Bond-009 approved these changes

2024-06-24 20:14 UTC, merged