Fix up getting livetv programs api docs
jellyfin/jellyfin pull request #12327
Opened 2024-07-23 17:35 UTC by crobibero

Functionally no different on the API side, but the api spec doesn't correctly reflect that the property is optional.

Requested here: https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/960#issuecomment-2176198249

2024-07-24 06:14 UTC, Shadowghost approved these changes

2024-07-24 11:16 UTC, Bond-009 approved these changes

2024-07-24 19:46 UTC, nielsvanvelzen requested changes
These should also be optional or have a default value in the OpenAPI spec:
- EnableTotalRecordCount
- LibrarySeriesId

2024-07-27 10:36 UTC, nielsvanvelzen approved these changes

2024-07-28 22:10 UTC, merged