Add OriginalLanguage as option to PreferredAudioLanguage
jellyfin/jellyfin pull request #12579
Opened 2024-09-04 18:33 UTC by Lampan-git

**Changes**
- Added originallanguage metadata tag and OriginalLanguage to items
- If OriginalLanguage is the picked option for PrefferedAudioLanguage, the originallanguage metadata is used.

2024-09-04 22:54 UTC, gnattu commented
Correct me if I'm wrong. So the new OriginalLanguage field comes solely from one of the metadata provider or user input right?

2024-09-05 07:23 UTC, Lampan-git commented
Yes. Omdb provides the metadata. As I barely understand the codebase, I added what was needed to get it working, and what felt fitting to do. Should there be any other providers added?

2024-10-08 11:00 UTC, FibreTTP commented
The Matroska format also supports flagging a track as the original language ([Ctrl+F for "FlagOriginal"](https://www.matroska.org/technical/elements.html)).

2024-10-08 12:53 UTC, Lampan-git commented
Good point, I did not know that. I will look into adding it as well. I don't know the order of priority though, if it should prefer the Jellyfin metadata or the Matroska one.

2024-10-08 13:09 UTC, foux commented
Not sure it's a great idea. Like for default track, people often set it without considering it. If you take it into account, it should definitely have a lesser priority than online sources IMHO.

2024-10-08 13:18 UTC, FibreTTP commented
The online metadata should definitely be higher priority.

2024-10-10 09:41 UTC, JPVenson commented
Please wait until #12798 is merged for this change.

2024-10-26 12:10 UTC, Lampan-git commented
I've added original indicator for audio now. It will prefer the metadata original language, but if there are two tracks matching the metadata original language where one has original indicator, it will prefer the one with the original indicator. If there is no metadata original language the original indicator stream will be picked regardless

2025-01-25 10:30 UTC, Lampan-git commented
> Please wait until #12798 is merged for this change.

I've updated the PR to work with the EFCore changes. So this shouldn't be blocked now

2025-03-26 18:35 UTC, JPVenson approved these changes

2025-07-14 19:58 UTC, shindouj commented
@JPVenson This seems to be unblocked for quite a while now - is there any reason for keeping it unmerged? I'm certain plenty of people would appreciate seeing this change.

2025-08-02 20:05 UTC, shindouj commented
Sorry to ping you @Bond-009 @Shadowghost @JPVenson - but I am trying to get some attention to merging this change. 

I am pretty sure the author will not be updating this PR forever, and since the change is small, it would be nice to either get it merged or at least directly rejected.

Thanks in advance for your time!

2025-10-27 16:52 UTC, Lampan-git commented
I’m not sure why the merge conflict label wasn’t removed. Everything should be updated

2025-12-24 22:05 UTC, winkado commented
Looking forward to this. LMK if I can help in any way

2025-12-24 22:30 UTC, Lampan-git commented
> Looking forward to this. LMK if I can help in any way

This only needs reviews. So either reviewing the code or just testing it to see that it works as expected would help.

2026-01-06 15:38 UTC, JPVenson approved these changes

2026-01-06 15:43 UTC, foux commented
Yay! Finally approved! Thanks

2026-03-28 17:06 UTC, shindouj commented
@Bond-009 @Shadowghost and any other reviewers of jellyfin/server that are not public - One and a half year in, do you think an approval and merge is possible? Or are user contributions just valued so low in Jellyfin? 

I truly do not understand at this point why can't you either say "We won't merge it" and close it or just approve and merge these changes. At the very least, an explanation or an acknowledgement would be appreciated. Both this PR and the jellyfin-web one look ready to go, with all comments addressed. I feel this is just disrespectful towards @Lampan-git's contribution and diligence at removing every conflict for a year and a half.

I'm really sorry if this message hits a nerve, but this PR being so blatantly ignored hits a nerve as well. If this is a matter of resources, I am happy to set a contribution to the project just to see this getting done. Thank you.

2026-03-29 01:00 UTC, winkado commented
well said @shindouj. There are plenty of users I personally know that want this feature. And out of those plenty are willing to contribute. At this point however it is up to the reviewers.

2026-04-07 01:23 UTC, CodeLtDave commented
I would love to see this in the next update. It's a simple change but it would make multi-language Jellyfin libraries so much more comfortable to watch.

I've tested this locally on my setup and it works great — original language tracks are picked up correctly from the metadata. No issues so far.

Would love to see this merged! 🙏

2026-05-02 19:07 UTC, retype2396 commented
Throwing a comment on here as well for support.  

The last big hurdle to make Jellyfin be the ultimate solution (at least for me) would be this, and it's disheartening to have watched it for 1.5 years and not seen it implemented.  I have spent so many hours trying to find an elegant and automatic solution to change default audio tracks, remove unneeded streams, and any other thing I can think of to try to make it so that by the time it gets to the player, it just plays the correct audio stream.  That said, more times than not English finds a way to be selected instead of whatever the native language is, which interrupts the experience.   

This seems like a great solution to a problem so many would have, and is deserving to be a "basic" feature of Jellyfin.  I eagerly await this to be resolved and merged!

2026-05-03 10:19 UTC, Bond-009 requested changes

2026-05-03 10:19 UTC, Bond-009 commented on Emby.Server.Implementations/Library/MediaSourceManager.cs
> +            if (user.AudioLanguagePreference == "OriginalLanguage")
Use string.Equals
Not just here, but for every string comparison

2026-05-03 21:22 UTC, Lampan-git commented
I have rebased ontop of master now that [Query Performance Improvements](https://github.com/jellyfin/jellyfin/pull/16062) is merged, so that the migrations are correct again.

2026-05-03 21:50 UTC, retype2396 commented
> I have rebased ontop of master now that [Query Performance Improvements](https://github.com/jellyfin/jellyfin/pull/16062) is merged, so that the migrations are correct again.

I forgot to add in my above comment, thank you lampan-git for all of your hard work on this! You and your efforts are appreciated!

2026-05-04 18:15 UTC, Bond-009 approved these changes

2026-05-05 20:31 UTC, nielsvanvelzen commented on Emby.Server.Implementations/Dto/DtoService.cs
> +                dto.OriginalLanguage = item.OriginalLanguage;
This data is clearly always available, so why do we need to request it explicitly via item fields?

2026-05-05 20:46 UTC, Lampan-git commented on Emby.Server.Implementations/Dto/DtoService.cs
> +                dto.OriginalLanguage = item.OriginalLanguage;
Fixed it

2026-05-06 17:06 UTC, nielsvanvelzen requested changes

2026-05-06 18:32 UTC, Lampan-git commented
I don't see any comments with the change request. Do you have any more info on what needs changing @nielsvanvelzen?

2026-05-06 19:43 UTC, nielsvanvelzen commented on MediaBrowser.Model/Querying/ItemFields.cs
> +        OriginalLanguage,
I don't think this is used anymore now that you removed the optional mapping

2026-05-06 19:43 UTC, nielsvanvelzen commented on MediaBrowser.Model/Querying/ItemFields.cs
> +        OriginalLanguage,
Idk why but GitHub didn't add this comment to my review. Here you go 😅

2026-05-06 19:50 UTC, Lampan-git commented on MediaBrowser.Model/Querying/ItemFields.cs
> +        OriginalLanguage,
Github being Github. Anyways, fixed it!

2026-05-06 20:05 UTC, nielsvanvelzen approved these changes
API changes look fine

2026-05-06 21:48 UTC, Lampan-git commented
Pretty sure the builds were failing because of https://github.com/jellyfin/jellyfin/pull/16789, but I guess they should be fixed now if rerun?

2026-05-07 18:07 UTC, merged