Add Dolby Vision tests for Tizen
jellyfin/jellyfin pull request #12670
Opened 2024-09-19 09:13 UTC by dmitrylyzo

**Changes**
- Fix Tizen H264 profiles.
- Add Dolby Vision tests for Tizen.

**Issues**
N/A

2024-09-19 09:22 UTC, gnattu commented
If you add `DOVIwithHLG`, `DOVIWithHDR10` and `DOVIWithSDR` to the supported range types, will profile 8 videos being directly played back? If so maybe we can just add those to prevent remuxing at all as Samsung TVs does not support Dolby Vision anyway and direct play the fallback layer is nothing to be worried about.

2024-09-20 00:16 UTC, dmitrylyzo commented
> If you add `DOVIwithHLG`, `DOVIWithHDR10` and `DOVIWithSDR` to the supported range types, will profile 8 videos being directly played back? If so maybe we can just add those to prevent remuxing at all as Samsung TVs does not support Dolby Vision anyway and direct play the fallback layer is nothing to be worried about.

Yes, it seems to work.
https://github.com/jellyfin/jellyfin-web/pull/6090

2024-09-22 02:01 UTC, crobibero approved these changes

2024-09-22 05:18 UTC, gnattu approved these changes

2024-09-22 05:21 UTC, gnattu requested changes
The old tizen3 stereo needs to updated to either apply max channel limit to direct play profile or we expect direct play. Current profile only applies stereo to transcoding profile.

2024-09-22 08:57 UTC, dmitrylyzo commented
> The old tizen3 stereo needs to updated to either apply max channel limit to direct play profile or we expect direct play. Current profile only applies stereo to transcoding profile.

Yeah, I am aware of that. I pushed changes, but it was late. 🛌 

I wanted to limit DirectPlay to Stereo, but I had to remove some tests. The same problem with Safari.

We can adjust Tizen 3 input data (set DirectPlay) to just make tests to pass.

2025-03-31 12:58 UTC, Bond-009 approved these changes

2025-03-31 16:35 UTC, gnattu approved these changes

2025-03-31 23:45 UTC, merged