Skip allowed tags check for parents of an item
jellyfin/jellyfin pull request #12721
Opened 2024-09-25 23:57 UTC by elfalem

The current logic is described in [this comment](https://github.com/jellyfin/jellyfin/issues/11869#issuecomment-2332871326). In short, the allowed tags check traverses the hierarchy of an item and checks all parents. This is usually desirable for blocked tags since an item shouldn't be visible if it or any of its parents are blocked. However, similar logic makes it cumbersome/impractical to use allowed tags because they would have to be applied to all parents an item in addition to the item.

**Changes**
The changes skip checking allowed tags on parents of an item. The item itself is still checked. No changes are made to blocked tags or parental ratings logic.

**Issues**
Fixes #11869

2024-09-25 23:58 UTC, elfalem commented on MediaBrowser.Controller/Entities/BaseItem.cs
> +            if (GetParents().Any(i => !i.IsVisible(user, true)))
This is the primary change of the PR.

2024-11-13 18:51 UTC, Shadowghost approved these changes

2024-11-19 16:58 UTC, JPVenson approved these changes

2024-12-07 21:33 UTC, JPVenson requested changes
new features may not target the current release branch

2024-12-07 21:45 UTC, elfalem commented
> new features may not target the current release branch

@JPVenson I'm not sure I understand. This is a bug fix for #11869, not a new feature.

2025-01-24 00:13 UTC, elfalem commented
@JPVenson if you could please take a look at my message above. I'm not sure there is a change to be made.

2025-01-24 06:07 UTC, JPVenson approved these changes

2025-02-09 16:48 UTC, crobibero approved these changes

2025-02-09 16:49 UTC, merged