Return channel groups
jellyfin/jellyfin pull request #12772
Opened 2024-10-04 17:15 UTC by joshjryan

LiveTV channels can optionally be grouped together. This is typically the case with M3U sources.

Jellyfin was already parsing the ChannelGroup out of the m3u, but the value was never returned to any API clients.  This change adds the ChannelGroup to Channel Items.

This will allow client applications to improve their UI by grouping channels and/or allowing users to filter by group.

2024-11-06 16:20 UTC, Shadowghost approved these changes

2025-01-08 19:42 UTC, topiga commented
Up

2025-01-09 16:01 UTC, Bond-009 approved these changes

2025-01-09 16:13 UTC, nielsvanvelzen requested changes
From a client developer perspective I can't do anything with this. At the very least the id of the channel should be used instead of the name. Additionally, I should be able to get all channel groups from the API, filter channels by group etc.

Otherwise this is just useless bloat on de baseitem model.

2025-01-09 16:26 UTC, joshjryan commented
Initially I submitted this because "if it's available, we might as well return it, just in a case a client wants it"...but @nielsvanvelzen is correct. There should also be an API endpoint to get the Channel Groups, sort by group, and filter by group.
I'll see if I can make time to re-do this PR to include those API additions.

2026-05-09 06:33 UTC, Bond-009 commented
Closing as stale, if you do end up reworking this PR please open a new one

2026-05-09 06:33 UTC, closed without merging