Add EpisodeExpression for anime file names
jellyfin/jellyfin pull request #12778
Opened 2024-10-06 07:13 UTC by TonyBotongChu

**Changes**
Add an EpisodeExpression to extract episode number from anime style file names like `[VCB-Studio] Re Zero kara Hajimeru Isekai Seikatsu [21][Ma10p_1080p][x265_flac]` and `[CASO&Sumisora][Oda_Nobuna_no_Yabou][04][BDRIP][1920x1080][x264_AAC][7620E503]`.

**Issues**

fixes issue #9332

2024-10-12 08:57 UTC, Bond-009 requested changes

2024-10-12 08:57 UTC, Bond-009 commented on Emby.Naming/Common/NamingOptions.cs
> +                new EpisodeExpression(@"(?:\[(?:[^\]]+)\]\s*)?(?<seriesname>\[[^\]]+\]|[^[\]]+)\s*\[(?<epnumber>\d+)\]")
Use `[0-9]` instead of `\d`

2024-10-12 09:10 UTC, TonyBotongChu commented on Emby.Naming/Common/NamingOptions.cs
> +                new EpisodeExpression(@"(?:\[(?:[^\]]+)\]\s*)?(?<seriesname>\[[^\]]+\]|[^[\]]+)\s*\[(?<epnumber>\d+)\]")
done

2024-10-12 11:24 UTC, Bond-009 approved these changes

2024-10-12 12:23 UTC, Shadowghost approved these changes

2024-10-19 07:47 UTC, TonyBotongChu commented
Hello @Bond-009 and @crobibero , just wanted to kindly check if there’s anything more needed from my side before this PR can be merged. It's already approved, so I thought I'd follow up in case it might have been missed. Thanks!

2024-10-19 08:06 UTC, nielsvanvelzen commented
The master branch is currently frozen for the 10.10 release so this PR is on-hold

2024-10-19 08:15 UTC, TonyBotongChu commented
> The master branch is currently frozen for the 10.10 release so this PR is on-hold

Thanks for the update! I'll keep an eye on it and will be ready if anything further is needed once the branch is unfrozen.

2024-11-02 12:46 UTC, TonyBotongChu commented
Hi team, seems new version has been released for a week, can this PR be merged now?

2024-11-03 14:44 UTC, merged