Added test for ListsingsManager.DeleteListingsProvider().
jellyfin/jellyfin pull request #12793
Opened 2024-10-08 16:59 UTC by kennethcochran

**Changes**
Addition of ListingsManagerTests to JellyFin.LiveTv.Tests project.
Addition of test for ListsingsManager.DeleteListingsProvider() to ListingsManagerTests.

**Issues**
N/A

2024-10-12 08:51 UTC, Bond-009 requested changes

2024-10-12 08:51 UTC, Bond-009 commented on tests/Jellyfin.LiveTv.Tests/Listings/ListingsManagerTests.cs
> +namespace Jellyfin.LiveTv.Tests.Listings
Use file scoped namespaces for new files

2024-10-12 08:51 UTC, Bond-009 commented on tests/Jellyfin.LiveTv.Tests/Listings/ListingsManagerTests.cs
> +            // Mock dependencies
```suggestion
```

2024-10-12 08:51 UTC, Bond-009 commented on tests/Jellyfin.LiveTv.Tests/Listings/ListingsManagerTests.cs
> +            Assert.DoesNotContain(_config.GetLiveTvConfiguration().ListingProviders, p => p.Id == id);
use string.Equals when comparing strings

2024-10-20 09:08 UTC, Bond-009 approved these changes

2024-11-04 06:31 UTC, JPVenson approved these changes

2024-11-04 07:42 UTC, Shadowghost approved these changes
@kennethcochran can you please fix the merge conflict?

2024-11-17 10:32 UTC, JPVenson approved these changes

2024-11-30 11:08 UTC, merged