Add ability to remove a ChannelMapping
jellyfin/jellyfin pull request #12970
Opened 2024-11-05 13:42 UTC by Giermann

Remove a ChannelMapping by selecting the same mapping again. This should be an intuitive way to de-select a mapping which currently requires the manual editing of a config file: https://forum.jellyfin.org/t-how-to-unmap-livetv-channels

**Changes**

**Issues**

2024-12-19 14:52 UTC, Shadowghost approved these changes
Seems like a reasonable change to me. But since I don't have any LiveTV to test with, I'd appreciate someone testing with a actual working setup 😄

2024-12-19 18:42 UTC, theguymadmax commented
I tested this, and it successfully removes the channel mapping as described.
![1](https://github.com/user-attachments/assets/0c51d2f3-a09d-45af-a0c1-be0a623f8fab)
![2](https://github.com/user-attachments/assets/5c8cadaa-34bf-411e-807e-6426274d3d24)

2024-12-20 21:24 UTC, Bond-009 requested changes
The exact count doesn't matter, just check if it exists

2024-12-20 21:24 UTC, Bond-009 commented on src/Jellyfin.LiveTv/Listings/ListingsManager.cs
> +            .Count(pair => string.Equals(pair.Name, tunerChannelNumber, StringComparison.OrdinalIgnoreCase)
```suggestion
        var channelMappingExists = listingsProviderInfo.ChannelMappings
            .Any(pair => string.Equals(pair.Name, tunerChannelNumber, StringComparison.OrdinalIgnoreCase)
```

2024-12-20 21:24 UTC, Bond-009 commented on src/Jellyfin.LiveTv/Listings/ListingsManager.cs
> +            && existingChannelMapping < 1)
```suggestion
            && !channelMappingExists)
```

2025-01-13 06:51 UTC, Giermann commented
Is there anything else for me to do?

2025-01-13 08:22 UTC, Shadowghost commented
The comments from Bond are not addressed, so at least those you should take care of 😄

2025-01-13 10:05 UTC, Bond-009 approved these changes

2025-01-15 10:26 UTC, merged