Fix InvariantCulture in VPP tonemap options
jellyfin/jellyfin pull request #12989
Opened 2024-11-08 14:02 UTC by nyanmisaka

**Changes**
- Fix InvariantCulture in VPP tonemap options

**Issues**
- Fixes #12988

2024-11-08 17:41 UTC, gnattu approved these changes

2024-11-08 18:58 UTC, Bond-009 requested changes
Did a quick benchmark with 3 arguments (a float, double and int)

| Method                  | Mean     | Error   | StdDev  | Gen0   | Allocated |
|------------------------ |---------:|--------:|--------:|-------:|----------:|
| InterpolWithToString    | 265.8 ns | 0.13 ns | 0.12 ns | 0.0052 |     280 B |
| InterpolWithFormattable | 285.5 ns | 0.60 ns | 0.56 ns | 0.0057 |     288 B |
| StringFormat            | 263.5 ns | 0.22 ns | 0.19 ns | 0.0038 |     208 B |

2024-11-08 18:59 UTC, Bond-009 commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                    procampParams += $"=b={options.VppTonemappingBrightness.ToString(CultureInfo.InvariantCulture)}";
Use `string.Format(CultureInfo.InvariantCulture, ...`

2024-11-09 18:31 UTC, crobibero approved these changes

2024-11-09 18:31 UTC, merged