Fix: remove spacial handling of <set> elements in NfoParser to enable unescaping of xml special characters
jellyfin/jellyfin pull request #13092
Opened 2024-11-23 00:33 UTC by TheMelmacian

**Changes**
- use `ReadNormalizedString` instead of `ReadInnerXml` method when parsing <set> element
  - `ReadNormalizedString` automatically unescapes all XML special characters
  - `ReadInnerXml` fails on invalid xml as well, so there is no advantage in using it
- removed `ParseSetXml` method from MovieNfoParser
  - special handling of the <set> element is unecessary since it can't prevent the XmlReader from switching into an error state after encountering invalid xml.
- added new test that checks if `&amp;` in collection name is correctly unescaped when parsed

**Issues**
Fixes #10767

2024-11-23 01:53 UTC, Shadowghost requested changes
I don't think that this works as intended. The code needs to properly parse two schemas:
```
<set>Test Collection</set>
```
and the Kodi NFO schema:
```
<set>
   <name></name>
   <overview></overview>
</set>
```

The writer should also write the latter one to adher to Kodi standards.

2024-11-23 03:50 UTC, gnattu requested changes
This indeed changes behavior and failed unit tests:

```

Jellyfin.XbmcMetadata.Tests.Parsers.MovieNfoParserTests.Fetch_Valid_Success [FAIL]
  Failed Jellyfin.XbmcMetadata.Tests.Parsers.MovieNfoParserTests.Fetch_Valid_Success [65 ms]
  Error Message:
   Assert.Equal() Failure: Values differ
Expected: 2017-11-15T00:00:00.0000000
Actual:   null
```

2024-11-23 10:42 UTC, TheMelmacian commented
Sorry, was late and I didn't check the other tests. I pushed a fix, that should work with both possible schemas.

2024-11-23 11:12 UTC, Shadowghost approved these changes

2024-12-01 18:23 UTC, TheMelmacian commented
> The writer should also write the latter one to adher to Kodi standards.

@Shadowghost The MovieNfoSaver currently writes the non Kodi variant to the nfo file: https://github.com/jellyfin/jellyfin/blob/9ae1ac2513e88a0897652c94abca712df18751a6/MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs#L116-L119

2024-12-01 19:08 UTC, Shadowghost commented
We should change that. If you want, you can do it in this PR, otherwise I'll take care of it later on another one.

2025-01-03 21:09 UTC, TheMelmacian commented
@gnattu If you have time, could you please review the changes?

2025-01-22 01:11 UTC, gnattu approved these changes

2025-01-22 16:42 UTC, Bond-009 approved these changes

2025-01-22 21:36 UTC, merged