Migrate keyframes to configured cache directory
jellyfin/jellyfin pull request #13125
Opened 2024-11-29 17:41 UTC by tcely

I'm not sure why these were put into the data directory in the first place.

The TODO comment about making it configurable is satisfied, for me, by using the already configurable cache directory instead.

**Changes**

Check for old keyframes json files in the data directory.
Only write new files to the cache directory.

**Issues**

2024-11-29 19:04 UTC, gnattu requested changes
These are technically metadata and not temporary data which should not be placed in cache.

2024-11-29 19:36 UTC, tcely commented
Alright. So, integrating these files into the also configurable metadata directory would be better?

2024-11-30 01:44 UTC, gnattu commented
> Alright. So, integrating these files into the also configurable metadata directory would be better?

Just keep where it is at the moment is good enough. Is there any specific reason you want to put those json file somewhere else that much?

2024-11-30 07:24 UTC, tcely commented
It's data that is rarely used that is uncompressed and unreferenced files aren't being cleaned up, so I'm trying to clear it out of the same location as the database file.

Attachments and subtitles seem to share the same condition. Having them on the same filesystem as my database just means there is less room for that file to grow.

2024-11-30 07:25 UTC, gnattu commented
> It's data that is rarely used

Except it is used for each and every remux playback

2024-11-30 07:28 UTC, tcely commented
Remix playback is happening much less often than browsing the library (database access) in my usage.

2024-11-30 07:38 UTC, tcely commented
> Keyframe data is meant to go into the db.

Hopefully, an external database is an option before that happens.

Needing a specific filesystem to support sqlite3 is why I'm not already moving my Jellyfin configuration into a larger shared filesystem.

2025-03-27 16:56 UTC, Shadowghost commented
This is obsolet once #13771 is merged

2025-04-03 00:17 UTC, closed without merging