Enable VideoToolbox AV1 decode
jellyfin/jellyfin pull request #13194
Opened 2024-12-09 08:22 UTC by gnattu

This decoder differs from others provided by VideoToolbox in that it lacks any software fallback. To achieve consistent behavior with other VideoToolbox decoders, this PR implemented additional checking on the server to simulate the software fallback provided by VideoToolbox.

The current fallback checking mechanism is a temporary solution. In the long term, it should be replaced with a more capable hardware capability checking system.

**Changes**

**Issues**

Required ffmpeg change is already backported here: https://github.com/jellyfin/jellyfin-ffmpeg/pull/500

The upstream has not released tagged version with VideoToolbox AV1 yet. Jellyfin-ffmpeg is required for now.

2024-12-23 20:29 UTC, Shadowghost approved these changes

2025-03-27 17:33 UTC, JPVenson approved these changes

2025-03-27 17:50 UTC, nyanmisaka approved these changes

2025-03-28 00:04 UTC, crobibero approved these changes

2025-03-28 13:00 UTC, Bond-009 requested changes

2025-03-28 13:00 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Encoder/ApplePlatformHelper.cs
> +    public static bool HasAv1HardwareAccel(ILogger logger)
Make sure we don't call this on an unsupported platform
```suggestion
    [SupportedOSPlatform("macos")]
    public static bool HasAv1HardwareAccel(ILogger logger)
```

2025-03-28 13:54 UTC, Bond-009 approved these changes

2025-03-30 21:12 UTC, merged