Fix missing episode removal
jellyfin/jellyfin pull request #13218
Opened 2024-12-13 13:09 UTC by Shadowghost

Missing episodes should be removed if the actual episode was added.

**Changes**
* Extend virtual episode removal to also take missing episodes into account

2024-12-20 21:43 UTC, Bond-009 requested changes

2024-12-20 21:43 UTC, Bond-009 commented on MediaBrowser.Providers/TV/SeriesMetadataService.cs
> +                var physicalEpisodes = seasonEpisodes.Except(nonPhysicalEpisodes);
I feel like there should exist a better way of doing this...
Worst case we write something ourselves.

2024-12-20 21:43 UTC, Bond-009 commented on MediaBrowser.Providers/TV/SeriesMetadataService.cs
> +                    }
I liked the previous control flow of this loop better, a single `DeleteEpisode` at the end and early exists if one of the criteria doesn't match

2024-12-30 09:55 UTC, Bond-009 approved these changes

2024-12-31 16:09 UTC, crobibero approved these changes

2024-12-31 16:09 UTC, merged