Fix OnPlaybackStopped task erroring out when closing a browser tab with a livestream that is transcoding
jellyfin/jellyfin pull request #13226
Opened 2024-12-14 21:22 UTC by timminator

This PR solves an issue where the OnPlaybackStopped task inside the SessionManager errors out as described in Issue #13225.

Changes:
This is done by adding a try-catch-block around the problematic function call. This should not result in any other issues when the task runs without this call succeeding. 

Issues:
Fixes #13225

2024-12-15 01:11 UTC, JPVenson requested changes

2024-12-15 01:11 UTC, JPVenson commented on Emby.Server.Implementations/Session/SessionManager.cs
> +                            mediaSource = await GetMediaSource(libraryItem, info.MediaSourceId, info.LiveStreamId).ConfigureAwait(false);
just catching the exception here, does not _solve_ the problem.
I would rather look into _why_ its throwing, it has have a reason.

2024-12-15 08:30 UTC, timminator commented
Thank you for taking a look at my PR.

The reason for this task erroring out I was able to figure out. I described it in the open Issue #13225:

What I found out:

- When a livestream is transcoding "Playback stopped" wont be reported immediately if the browser tab is closed.
- Then the Task "CloseIfNeededAsync" is called.
This triggers the CloseLivestream task which removes the livestreamid out of the _openStreams dictionary.
- The OnPlaybackStopped function eventually calls the task "GetLiveStreamWithDirectStreamProvider"
- There you find the following line of code: "// TODO probably shouldn't throw here but it is kept for "backwards compatibility""
- This function is throwing because the livestreamid was already removed from the dictionary by CloseLivestream and GetLiveStreamInfo(id) returns null.

This problem is very closely related to the other issue #13219 and PR request #13220 I opened a few days ago.
It would also be a possibility to allow the task "GetLiveStreamWithDirectStreamProvider" to return null, but then the other tasks using this one, would need to be able to handle this case aswell.
I thought it would be easier to do it like this, because we know the reason why it happens and why it is needed for this edge case.
I'm interested in your feedback and your thoughts on this.

2024-12-15 13:38 UTC, JPVenson commented
> It would also be a possibility to allow the task "GetLiveStreamWithDirectStreamProvider" to return null, but then the other tasks using this one, would need to be able to handle this case aswell.
I thought it would be easier to do it like this, because we know the reason why it happens and why it is needed for this edge case.
I'm interested in your feedback and your thoughts on this.

I looked into it and found that #6538 added that throw, i also taked to the author but he cannot remember _what_ we are supporting with that.

Instead of adding yet another quickfix ontop of all of this, i would go with fixing all callers here just beeing able to handle a null value instead and just make it right this time.

2025-02-28 01:33 UTC, timminator commented
Sorry for the long time without any updates. I ran into another weird issue with Jellyfin closely related to this and stopped working on it.
Today I worked on it again and I was able to find the root cause of my new issue. I opened another issue #13634 for that.
While I was able to find out the root cause, I'm not able to come up with a solution. I would appreciate if you could read through that issue aswell.

Now to this PR: I updated it to actually handle the null value now. It did also not require a lot of changes. I just had to add a few early returns in the sessionmanager, because by abruptly closing the tab the session got removed, but the tasks where not stopped at that point. That all worked fine and now the log does no longer show any errors:


```
[00:54:26] [INF] [13] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Stopping ffmpeg process with q command for C:\Users\GPUVM\AppData\Local\jellyfin\cache\transcodes\0dddba921d2da1b7d75ce88bb3ae6c98.m3u8
[00:54:26] [INF] [18] Emby.Server.Implementations.Library.MediaSourceManager: Live stream a30d2ab40a1c24c15fb07e9537d38205 consumer count is now 0
[00:54:26] [INF] [18] Emby.Server.Implementations.Library.MediaSourceManager: Closing live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_a30d2ab40a1c24c15fb07e9537d38205
[00:54:26] [INF] [18] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Closing LiveStream
[00:54:26] [INF] [18] Emby.Server.Implementations.Library.MediaSourceManager: Live stream e2329f4997b378e64ccf8fa396deb76e_af999c25a00715699361240d4c6c7a53_a30d2ab40a1c24c15fb07e9537d38205 closed successfully
[00:54:26] [INF] [18] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.11.11 closed
[00:54:31] [INF] [13] MediaBrowser.Controller.MediaEncoding.TranscodingJob: Killing FFmpeg process for C:\Users\GPUVM\AppData\Local\jellyfin\cache\transcodes\0dddba921d2da1b7d75ce88bb3ae6c98.m3u8
[00:54:31] [INF] [13] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) C:\Users\GPUVM\AppData\Local\jellyfin\cache\transcodes\0dddba921d2da1b7d75ce88bb3ae6c98.m3u8
[00:54:31] [ERR] [13] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code -1
[00:54:32] [INF] [13] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.10.0 playing Stream1. Stopped at 2417 ms
```

2025-03-10 07:48 UTC, JPVenson approved these changes

2025-03-15 17:12 UTC, timminator commented
@JPVenson Could you request a review from a Team member? I would appreciate it. :-)

2025-03-16 16:37 UTC, Shadowghost approved these changes

2025-03-20 09:46 UTC, Bond-009 approved these changes

2025-03-20 09:46 UTC, Bond-009 commented on Emby.Server.Implementations/Library/MediaSourceManager.cs
> +            if (info == null)
```suggestion
            var info = GetLiveStreamInfo(id);
            if (info is null)
```

2025-03-20 09:46 UTC, Bond-009 commented on Emby.Server.Implementations/Session/SessionManager.cs
> +            if (session == null)
```suggestion
            if (session is null)
```

2025-03-20 09:46 UTC, Bond-009 commented on Emby.Server.Implementations/Session/SessionManager.cs
> +            if (session == null)
```suggestion
            if (session is null)
```

2025-03-20 09:46 UTC, Bond-009 commented on Emby.Server.Implementations/Session/SessionManager.cs
> +            if (session == null)
```suggestion
            var session = GetSession(info.SessionId, false);
            if (session is null)
```

2025-03-20 10:16 UTC, timminator commented
Thanks for the review. I updated the commit with the suggested changes.

2025-03-20 13:10 UTC, crobibero approved these changes

2025-03-20 13:10 UTC, crobibero commented
@timminator for future PRs please refrain from force-pushing as it causes a full re-review :)

2025-03-20 13:10 UTC, merged