Improve dynamic HDR metadata handling
jellyfin/jellyfin pull request #13277
Opened 2024-12-23 10:45 UTC by gnattu

**Changes**

This is a relatively big change to the way advanced HDR formats are handled. Previously, we were only checking HDR10, HLG, and Dolby Vision files, with a naive mapping of fallbacks. While this approach was somewhat effective, we continue to encounter compatibility issues. This PR addresses these issues by:

- Properly detecting HDR10+ videos and assigning the corresponding `VideoRangeType`.
- Introducing additional Dolby Vision `VideoRangeType` variants to address common compatibility issues, such as Profile 7 videos, videos with invalid or out-of-specification profile values, and Dolby Vision HDR10+ hybrid videos.
- Implementing a functionality to remove dynamic HDR metadata (Dolby Vision or HDR10+) when necessary to mitigate compatibility issues from the client side.

Metadata rescan on the already index problematic files would be necessary.

Current implementation is abusing the EL flag field to avoid changing the database schema. Should add a proper field once #12798 is merged.

**Issues**

Depends on https://github.com/jellyfin/jellyfin-ffmpeg/pull/519

Fixes jellyfin/jellyfin-androidtv#4021
Fixes jellyfin/jellyfin-androidtv#2700
Fixes jellyfin/jellyfin-androidtv#2630
Fixes #11275

Closes feature request: https://features.jellyfin.org/posts/2557/support-for-playing-dv-profile-7-hybrid-dv-hdr-files-on-non-dv-hdr-device

2024-12-31 10:31 UTC, gnattu commented
Most of the part of this PR other than the EL flag hack to not change current DB schema is in good shape.
I made preliminary docker image tarball here if someone is willing to test if this indeed fixed the compatibility issues:

https://github.com/gnattu/jellyfin/releases/tag/master-dynamic-hdr

As always, never run unstable images on your current database. Run it fresh in an isolated environment.

2025-01-02 17:26 UTC, theguymadmax commented
Are there any other changes in your Docker image aside from this PR and the updated FFmpeg package? I built it from source to test.

AndroidTV logs:
```
Transformed with default transformers response body for http://192.168.1.5\:8096/Items/c88d15650-93b5-a57f-9e1a-3c56g0e08918 to interface io.ktor.utils.io.ByteReadChannel (Kotlin reflection is not available)
Deserialization failed
kotlinx.serialization.SerializationException: org.jellyfin.sdk.model.api.VideoRangeType does not contain element with name 'DOVIWithHDR10Plus' at path $.MediaSources[0].MediaStreams[0].VideoRangeType
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:107)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(StreamingJsonDecoder.kt:352)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:136)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:102)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at org.jellyfin.sdk.model.api.MediaStream$$serializer.deserialize(MediaStream.kt:19)
	at org.jellyfin.sdk.model.api.MediaStream$$serializer.deserialize(MediaStream.kt:19)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at org.jellyfin.sdk.model.api.MediaSourceInfo$$serializer.deserialize(MediaSourceInfo.kt:17)
	at org.jellyfin.sdk.model.api.MediaSourceInfo$$serializer.deserialize(MediaSourceInfo.kt:17)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
	at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
	at org.jellyfin.sdk.api.operations.UserLibraryApi.getItem(UserLibraryApi.kt:343)
	at org.jellyfin.sdk.api.operations.UserLibraryApi$getItem$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Failed to refresh item
org.jellyfin.sdk.api.client.exception.InvalidContentException: Deserialization failed
	at org.jellyfin.sdk.api.operations.UserLibraryApi.getItem(UserLibraryApi.kt:347)
	at org.jellyfin.sdk.api.operations.UserLibraryApi$getItem$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: kotlinx.serialization.SerializationException: org.jellyfin.sdk.model.api.VideoRangeType does not contain element with name 'DOVIWithHDR10Plus' at path $.MediaSources[0].MediaStreams[0].VideoRangeType
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:107)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(StreamingJsonDecoder.kt:352)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:136)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:102)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at org.jellyfin.sdk.model.api.MediaStream$$serializer.deserialize(MediaStream.kt:19)
	at org.jellyfin.sdk.model.api.MediaStream$$serializer.deserialize(MediaStream.kt:19)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSer [...]

2025-01-02 17:28 UTC, gnattu commented
Well, unfortunately android TV needs to be modified to try this then as its SDK has strict requirements for enum unlike web simply interprets them as string.

2025-01-07 06:32 UTC, Dnkhatri commented
I think this should fix these android tv issues as well.  A very large portion of issues on jellyfin android tv player that are opened are I think related to this. But it seems to be a big change on how jellyfin works so probably wont be quick fix.  

https://github.com/jellyfin/jellyfin-androidtv/issues/3992
https://github.com/jellyfin/jellyfin-androidtv/issues/4185
https://github.com/jellyfin/jellyfin-androidtv/issues/4018
https://github.com/jellyfin/jellyfin-androidtv/issues/4387

2025-01-17 18:52 UTC, DerNiccoo commented
Hey, I encounter this problem a lot and don't really know which videos will play and which won't. I really hope this will fix it, but are there any updates here?

2025-01-17 19:12 UTC, gnattu commented
> Hey, I encounter this problem a lot and don't really know which videos will play and which won't. I really hope this will fix it, but are there any updates here?

Due to the potential change to the database schema this might be blocked by #12798 unless we want to ship with the EL bit hack as is.

To test this on Android TV devices we have to build clients using a new SDK that accepts the new range types which is still missing.

The actual land date is still uncertain because of the EF Core migration is already so big for next major release.

2025-01-17 19:25 UTC, DerNiccoo commented
Thanks for the update! Good to hear, that it is not forgotten. And yes, the migration looks really big. Glad I don't have to review it.

2025-01-17 20:49 UTC, theguymadmax commented
I made a local copy of the Jellyfin SDK for Kotlin with the updated ranges and was able to test it. Previously, when attempting to play DV/HDR10+ files, the screen would flicker (like when changing refresh rates), and then the entire screen would turn black or magenta. The interface would become unresponsive, and you couldn’t interact with controls (play, pause, etc.). The video would be black with audio playing, and you'd have to back out using the remote to return to the Jellyfin media info screen.

Now, there’s no flicker, and the movie starts playing, but the video is still just a black screen with audio. However, the UI controls are responsive and working as expected.

Media info of test media from Jellyfin: 
```
Video
Title: 4K HEVC Dolby Vision Profile 8.1 (HDR10)
Codec: HEVC
AVC: No
Profile: Main 10
Level: 150
Resolution: 3840x1608
Aspect ratio: 2.40:1
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 24618 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: DOVIWithHDR10Plus
DV title: Dolby Vision Profile 8.1 (HDR10)
DV version major: 1
DV version minor: 0
DV profile: 8
DV level: 6
DV rpu preset flag: 1
DV el preset flag: 2
DV bl preset flag: 1
DV bl signal compatibility id: 1
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1
```

2025-01-17 20:59 UTC, gnattu commented
@theguymadmax Can you try use the ffmpeg from here and see if that resolves the issue: https://github.com/jellyfin/jellyfin-ffmpeg/pull/526

2025-01-17 22:29 UTC, theguymadmax commented
Ok, I need to scratch my previous comment. I mistakenly tested with the wrong Firestick model. I used the 1st-gen 4K Firestick instead of the 2nd-gen 4K. After retesting with the 2nd-gen, I observed no changes in behavior, even after updating to the newer version of FFmpeg.

The 1st-gen 4k has the black video bug but the UI is responsive unlike the 2nd-gen, so there was no change there either. 

I think the ATV client sends DV/HDR metadata to the player without a check to see if it's compatible. As I can send DV/HDR media to another device that supports 4k resolution but not DV/HDR. The file directly plays without error with washed-out or a green tint depending on the HDR type. If the server needs to know from the client what type of HDR metadata is supported, then I think there's some work to be done on the client side.

2025-01-18 09:37 UTC, gnattu commented
> Ok, I need to scratch my previous comment. I mistakenly tested with the wrong Firestick model. I used the 1st-gen 4K Firestick instead of the 2nd-gen 4K. After retesting with the 2nd-gen, I observed no changes in behavior, even after updating to the newer version of FFmpeg.
> 
> The 1st-gen 4k has the black video bug but the UI is responsive unlike the 2nd-gen, so there was no change there either.
> 
> I think the ATV client sends DV/HDR metadata to the player without a check to see if it's compatible. As I can send DV/HDR media to another device that supports 4k resolution but not DV/HDR. The file directly plays without error with washed-out or a green tint depending on the HDR type. If the server needs to know from the client what type of HDR metadata is supported, then I think there's some work to be done on the client side.

Direct play? That should not happen. The file should be played as remux to have the server to process the dynamic hdr metadata.

2025-02-06 00:54 UTC, losuler commented
I was eager to test these changes out, so I built the docker image[^1] just changing the submodule path `jellyfin-server` so it pointed to this branch[^2], and ran the resulting image in a fresh isolated environment. Assuming I did this correctly (and there wasn't any else I needed to modify for the build), everything looked and played fine in my browser, but on my Fire TV Stick 4K (Gen 2) I had issues.

For movies that I hadn't got the metadata for yet, playing them exhibited the same issues as before where the DV layer was being sent to my HDR TV (blank screen, messed up rendering, etc). After waiting for all the metadata to be downloaded, I can see the main screen, but clicking the library leads to a library view that's devoid of any movies. On the main screen, clicking any movies in the recently added section causes the UI to refresh and nothing to happen. Holding down on those movies and choosing play causes the app to crash with the attached log[^3].

Happy to correct my build if I did anything wrong, or to test yours once you rebuild it with the recent commits. I also removed the server from the app and re-added it multiple times and rebooted the Fire Stick at the same time, in case that was causing any issues, but neither helped.

[^1]: https://github.com/jellyfin/jellyfin-packaging
[^2]: https://github.com/gnattu/jellyfin/tree/hdr-metadata-handling
[^3]: [upload_org.jellyfin.androidtv_0.18.4_20250205184528_606f08fb724645609907c0768649f6d8.log](https://github.com/user-attachments/files/18681168/upload_org.jellyfin.androidtv_0.18.4_20250205184528_606f08fb724645609907c0768649f6d8.log)

2025-02-06 00:57 UTC, gnattu commented
As I said earlier AndroidTV client should play those videos as remux instead of just direct play it. If you cannot see an ffmpeg log on the server shows remux/directstream for your playback your client is not asking the server to do a remux and the server cannot remove the incompatible metadata for the clients.

2025-02-06 01:20 UTC, losuler commented
Sorry for the noise then. I guess I was a little too eager and skimmed over the previous conversations. I guess I'll have to wait for the appropriate changes to reach the Android TV client, given I have the same model Fire Stick as @theguymadmax.

2025-03-01 00:16 UTC, soultaco83 commented
So far I have installed and the videos that were just purple and pink appear to be properly colored. 
I have only tested 2, but with the 10 friends I have on my server. The reports have lowered.

2025-03-27 17:46 UTC, JPVenson requested changes
Still missing EFCore migration for `MediaStreamInfo.Hdr10PlusPresentFlag` otherwise good

2025-03-27 17:48 UTC, gnattu commented
> Still missing EFCore migration for `MediaStreamInfo.Hdr10PlusPresentFlag` otherwise good

Added

2025-03-27 17:54 UTC, JPVenson approved these changes

2025-03-27 18:49 UTC, nyanmisaka approved these changes

2025-03-27 22:26 UTC, Shadowghost approved these changes

2025-03-28 14:06 UTC, Bond-009 requested changes

2025-03-28 14:06 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
> +        private static readonly Dictionary<int, string[]> _bsfOptionsDict = new Dictionary<int, string[]>
Why int instead of the enum?

2025-03-28 18:56 UTC, nielsvanvelzen commented on Jellyfin.Data/Enums/VideoRangeType.cs
> +
Adding new enum members to an enum used in response model with no nullability or default value, like this one, is a breaking API change.
I'd like to avoid this for 10.11 so our clients can keep compatibility with both 10.10 and 10.11 as there is a significant database refactor.

If we want to avoid this in the future we should add a new "Unknown" member and use that as default value, or make the usages of this enum nullable.

2025-03-28 20:38 UTC, gnattu commented on Jellyfin.Data/Enums/VideoRangeType.cs
> +
Except it does have a value "Unknown" already?

2025-03-28 20:53 UTC, gnattu commented on MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
> +        private static readonly Dictionary<BitStreamFilterOptionType, string[]> _bsfOptionsDict = new Dictionary<BitStreamFilterOptionType, string[]>
This is still to be discussed though, we *may* have more complicated bitstream filters in the future where the test needs to be performed differently with combined option which makes an array more useful. For current usage yes the tuple is better.

2025-03-28 20:55 UTC, nielsvanvelzen commented on Jellyfin.Data/Enums/VideoRangeType.cs
> +
Talking from an API perspective so it is somewhat different. The generated OpenAPI specification does not have a default value set for `MediaStream.videoRangeType`. To make that work we need to assign a default value or use the `[DefaultValue]` attribute on that property.

Right now the API specification is telling us "MediaStream.videoRangeType` is not null and has no default value. Therefor the SDK's are unable to fallback to a safe value if it receives an "unknown" value. I could make changes to our Kotlin SDK to always use "unknown" as default if that member exists but other OpenAPI code generators won't be able to figure out that behavior.

2025-03-28 21:04 UTC, gnattu commented on Jellyfin.Data/Enums/VideoRangeType.cs
> +
I marked `VideoRangeType.Unknown` explicitly as default on api models using this enum. The more problematic thing is I *think* most if not all enums being used in API models that is not nullable already has its own implicit default value but not exposed to API yet. Is there any easy way to get all such APIs so that we can fix those at once?

2025-03-31 14:31 UTC, nielsvanvelzen commented on MediaBrowser.Controller/MediaEncoding/EncodingJobInfo.cs
> +        [DefaultValue(VideoRangeType.Unknown)]
This is not an API model

2025-03-31 14:31 UTC, nielsvanvelzen commented on MediaBrowser.Model/Dlna/StreamInfo.cs
> +    [DefaultValue(VideoRangeType.Unknown)]
This is not an API model

2025-03-31 14:33 UTC, nielsvanvelzen commented on Jellyfin.Data/Enums/VideoRangeType.cs
> +
Model properties that are non-nullable using an enum that has an Unknown member in 10.10:

```
BaseItemDto.mediaType
BaseItemPerson.type
MediaSegmentDto.type
MediaStream.videoRange
MediaStream.videoRangeType
SearchHint.mediaType
```

2025-03-31 17:40 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
> +        private static readonly Dictionary<BitStreamFilterOptionType, string[]> _bsfOptionsDict = new Dictionary<BitStreamFilterOptionType, string[]>
For now I'd prefer a tuple as doing `.Where(item => item.Value.Length == 2)` on static data seems a bit silly

2025-04-02 12:33 UTC, Bond-009 approved these changes

2025-04-03 00:06 UTC, merged

2025-06-08 06:43 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
In 10.11 RC1, DOVI P5 remuxing was mistakenly enabled on Chrome. cc @gnattu

For this case, `dynamicHdrMetadataRemovalPlan` is None and `CanEncoderRemoveDynamicHdrMetadata()` is true.

2025-06-08 07:41 UTC, gnattu commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
How could it be though? Why Chrome would report it supports dolby vision in the first place?

2025-06-08 07:44 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
It doesn't, it only reports SDR, HDR10 and HLG. Reproduced this on a fresh install of 10.11 RC1.

2025-06-08 07:45 UTC, gnattu commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
Alright. Let me check where the problem is.

2025-06-16 09:59 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
![image](https://github.com/user-attachments/assets/be940ba3-a31f-4d1b-a6e3-8da3e1c5b0fe)

Found another issue related to this codeblock. Firefox enabled HEVC decoding no long ago, but it has no client side tone-mapping support, so the server should NOT remux HDR content. cc @gnattu

2025-06-16 10:15 UTC, gnattu commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
Then it should not report HDR supporting at all shouldn't it?

2025-06-16 10:38 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
> Then it should not report HDR supporting at all shouldn't it?

Yes, it doesn't report any HDR support because Firefox has been hardcoded to SDR only in web.

2025-06-16 10:41 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                        return false;
![image](https://github.com/user-attachments/assets/9b9342d4-6380-441d-8633-5aa05870ca07)

2025-08-18 04:26 UTC, Dnkhatri commented
still not working in some cases 
https://github.com/jellyfin/jellyfin-androidtv/issues/4860#issuecomment-3194631812