Fix DTS in HLS
jellyfin/jellyfin pull request #13288
Opened 2024-12-27 11:47 UTC by Shadowghost

`DTS` should usually have codec name `dts` and encoder `dca`. We're currently only adding `dca` to the codec list which prevents remuxing of DTS when streaming via fMP4.

I'm not sure if we can just remove `dca` from the codec checks.

**Changes**
* Add `dts` to supported HLS audio codecs and shift logic
* Remove check skipping any `GreaterThanEqual` conditions in transcoding conditions, currently preventing processing later down the callstack of those conditions

2024-12-27 12:45 UTC, Bond-009 approved these changes

2024-12-27 16:48 UTC, gnattu requested changes
I think we can just drop dca from the list as it should always be dts.

2024-12-27 16:48 UTC, gnattu commented on MediaBrowser.Model/Dlna/StreamBuilder.cs
> +        private static readonly string[] _supportedHlsAudioCodecsMp4 = ["aac", "ac3", "eac3", "mp3", "alac", "flac", "opus", "dca", "dts", "truehd"];
```suggestion
        private static readonly string[] _supportedHlsAudioCodecsMp4 = ["aac", "ac3", "eac3", "mp3", "alac", "flac", "opus", "dts", "truehd"];
```

2024-12-27 16:48 UTC, gnattu commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
>                  shiftAudioCodecs.Add("dca");
```suggestion
```

2024-12-27 16:48 UTC, gnattu commented on MediaBrowser.Model/Dlna/StreamBuilder.cs
> -
Don't change such behavior in bugfix releases as it might break some weird clients.

2024-12-27 17:34 UTC, gnattu requested changes

2024-12-27 17:34 UTC, gnattu commented on Jellyfin.Api/Controllers/DynamicHlsController.cs
I'm not a big fan of having so many cosmetic changes on unrelated files. This will cause numerous merge conflicts for backporting and would require rebasing for current PRs.

2024-12-27 17:40 UTC, Shadowghost commented on Jellyfin.Api/Controllers/DynamicHlsController.cs
I totally agree. Currently not on my main rif and apparently auto-fromat was enabled. Fixed it.

2024-12-27 17:41 UTC, gnattu approved these changes

2024-12-29 21:30 UTC, Bond-009 approved these changes

2024-12-29 21:31 UTC, Bond-009 approved these changes

2024-12-31 16:10 UTC, crobibero approved these changes

2024-12-31 16:10 UTC, merged