Make MusicBrainzAlbumProvider thread safe and fix retry logic
jellyfin/jellyfin pull request #4261
Opened 2020-10-03 00:25 UTC by Spacetech

Related to #4242, and similar to #4223. 
Fixes issues when refreshing multiple items at the same time for musicbrainz. Unfortunately due to musicbrainz api limits, it seems like we need to keep this running sequentially.

Also fixes the retry logic - it's currently broken and throws this error whenever it tries the same request again:

```
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMusicBrainzResponse(String url, CancellationToken cancellationToken) in C:\Programming\jellyfin\MediaBrowser.Providers\Plugins\MusicBrainz\MusicBrainzAlbumProvider.cs:line 774
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetReleaseResult(String albumName, String artistId, CancellationToken cancellationToken) in C:\Programming\jellyfin\MediaBrowser.Providers\Plugins\MusicBrainz\MusicBrainzAlbumProvider.cs:line 285
   at MediaBrowser.Providers.Music.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo id, CancellationToken cancellationToken) in C:\Programming\jellyfin\MediaBrowser.Providers\Plugins\MusicBrainz\MusicBrainzAlbumProvider.cs:line 213
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken) in C:\Programming\jellyfin\MediaBrowser.Providers\Manager\MetadataService.cs:line 853
```

**Changes**
- Add a semaphore to only allow a single request at a time.
- Fix music brainz retry logic.

**Issues**
None

2020-10-03 01:19 UTC, dkanada commented
Since you're having to make changes within the providers themselves, it sounds like even the non-core providers will need thread safety before we can parallelize the scanner.

2020-10-03 01:37 UTC, Spacetech commented
> 
> 
> Since you're having to make changes within the providers themselves, it sounds like even the non-core providers will need thread safety before we can parallelize the scanner.

Yea I agree. I have been testing different types of libraries with different providers enabled in an attempt to find these issues. The TvDb provider and this one had obvious issues. I am somewhat worried there are issues in others too, but they might not be as visible (maybe they are rare race conditions).

Any suggestions for how to roll out the parallel scanner change? I'm not certain I will be able to find all these issues myself. If we are concerned about this, maybe we could merge the parallelized scanner change with the default concurrency set to 1, so the scanner would essentially remain sequential. Then users could change the config value to make it parallel and report back if they find issues?
I would certainly attempt to fix issues in any providers that are not working correctly with the parallelized scanner.

2020-10-03 02:31 UTC, barronpm approved these changes

2020-10-16 09:40 UTC, BaronGreenback requested changes

2020-10-16 09:40 UTC, BaronGreenback commented on MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
> +                        // MusicBrainz is extremely adamant about limiting to one request per second
```suggestion
                        // MusicBrainz is extremely adamant about limiting to one request per second.
```

2020-10-16 09:40 UTC, BaronGreenback commented on MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
> +                    // We retry a finite number of times, and only whilst MB is indicating 503 (throttling)
```suggestion
                    // We retry a finite number of times, and only whilst MB is indicating 503 (throttling).
```

2020-10-16 09:40 UTC, BaronGreenback commented on MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
> +                    // https://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting#User-Agent
```suggestion
                    // https://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting#User-Agent .
```

2020-10-16 09:40 UTC, BaronGreenback commented on MediaBrowser.Providers/Plugins/MusicBrainz/MusicBrainzAlbumProvider.cs
> +                // Log error if unable to query MB database due to throttling
```suggestion
                // Log error if unable to query MB database due to throttling.
```

2020-10-16 20:20 UTC, BaronGreenback approved these changes

2020-10-17 05:58 UTC, merged