Make tmdb api key configurable
jellyfin/jellyfin pull request #4287
Opened 2020-10-06 13:04 UTC by Bond-009

2020-10-06 18:17 UTC, cvium commented on Emby.Server.Implementations/ConfigurationOptions.cs
> +            { TmdbApiKeyKey, "4219e299c89411838049ab0dab19ebd5" }
Ideally the providers should be separate plugins.

2020-10-06 20:47 UTC, crobibero approved these changes

2020-10-11 09:36 UTC, dkanada reviewed
This should really be using the existing plugin configuration pages like the other providers that allow custom API keys.

2020-11-19 10:52 UTC, cvium requested changes
The goal is to split providers into plugins. This PR is not conducive to that goal.

2020-11-19 10:58 UTC, dkanada commented
If this moves to the TMDB plugin configuration though, it would be fine. Either it already exists (about half of the bundled plugins implement IPluginConfiguration) or it could be added relatively easily.

2020-11-21 20:03 UTC, joshuaboniface commented
Yea I think this can be closed with the removal of TMDB in #4530. Gonna close it.

2020-11-21 20:03 UTC, closed without merging