Remove TheTVDB plugin from server source.
jellyfin/jellyfin pull request #4298
Opened 2020-10-09 13:43 UTC by crobibero

Depends on #4253

Replaced by https://github.com/crobibero/jellyfin-plugin-tvdb

2020-11-15 20:50 UTC, barronpm requested changes

2020-11-15 20:50 UTC, barronpm commented on Jellyfin.Server/Migrations/MigrationRunner.cs
> +            typeof(Routines.MigrateDisplayPreferencesDb),
Duplicated line

2020-11-15 20:52 UTC, barronpm approved these changes

2020-11-18 08:26 UTC, BaronGreenback approved these changes

2020-11-19 19:24 UTC, joshuaboniface approved these changes

2020-11-19 19:25 UTC, merged