Making default Plugin configurations accessible when developing.
jellyfin/jellyfin pull request #4339
Opened 2020-10-16 14:05 UTC by BaronGreenback

A configuration file is only ever created if the plugin provides a method of updating its settings.

This change ensures that when a plug configuration is created for the first time, its settings are stored to disk.

This should make it easier to develop plugins.

2020-10-28 23:51 UTC, crobibero commented
I don't think this change is needed, if a plugin has a configuration that the user can edit the plugin should provide a way to change it without manually editing the file

2020-10-29 09:58 UTC, BaronGreenback commented
I was thinking more from the dev side of things than the usrr. It means i can write the plugin settings class then concentrate and test plugin development and get that working before moving to add the web section.

Yes a could create a xml file manually but thats a pain and can be prone to errors and besides -  i'm lazy! Anything that can help speed up my dev and testing is good for me.

2020-11-19 08:08 UTC, oddstr13 requested changes

2020-11-19 08:08 UTC, oddstr13 commented on MediaBrowser.Common/Plugins/BasePlugin.cs
> +        public virtual void SaveConfiguration(TConfigurationType config)
This function is called directly in some plugins.
Maybe add a function overload?
```
$ grep 'SaveConfiguration()' . -r
./jellyfin-plugin-intros/Jellyfin.Plugin.Intros/IntroManager.cs:            Plugin.Instance.SaveConfiguration();
./jellyfin-plugin-iptv/MediaBrowser.Channels.IPTV/Api/ServerApiEndpoints.cs:            Plugin.Instance.SaveConfiguration();
./jellyfin-plugin-trakt/Trakt/Api/ServerApiEndpoints.cs:                Plugin.Instance.SaveConfiguration();
./jellyfin-plugin-trakt/Trakt/Api/TraktApi.cs:                            Plugin.Instance.SaveConfiguration();
./jellyfin-plugin-trakt/Trakt/Api/TraktApi.cs:                Plugin.Instance.SaveConfiguration();
```

2020-11-20 00:44 UTC, crobibero approved these changes
Would be simpler to call the new function with the parameter

2020-11-20 07:43 UTC, oddstr13 commented
> Would be simpler to call the new function with the parameter

Yes, this is what I meant when I said overload – either way works, even if I think this makes for cleaner and more easily maintainable code

```csharp
public virtual void SaveConfiguration()
{
     SaveConfiguration(Configuration);
}
```

2020-11-20 07:44 UTC, oddstr13 approved these changes

2020-11-20 09:03 UTC, BaronGreenback commented
> > Would be simpler to call the new function with the parameter
> 
> Yes, this is what I meant when I said overload – either way works, even if I think this makes for cleaner and more easily maintainable code
> 
> ```cs
> public virtual void SaveConfiguration()
> {
>      SaveConfiguration(Configuration);
> }
> ```

Brain fart - updated code.

2020-11-20 17:34 UTC, merged