Add BaseItemManager
jellyfin/jellyfin pull request #4342
Opened 2020-10-18 02:03 UTC by crobibero

2020-10-26 00:38 UTC, barronpm commented on Jellyfin.Server/CoreAppHost.cs
> +            ServiceCollection.AddScoped<IBaseItemManager, BaseItemManager>();
This should be a singleton until everything that depends on it is made scoped

2020-10-28 00:03 UTC, barronpm approved these changes

2020-11-08 09:50 UTC, BaronGreenback requested changes

2020-11-08 09:50 UTC, BaronGreenback commented on MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
> +                // hack alert
```suggestion
                // Hack alert.
```

2020-11-08 09:50 UTC, BaronGreenback commented on MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
> +                // hack alert
```suggestion
                // Hack alert.
```

2020-11-08 09:50 UTC, BaronGreenback commented on MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
> +                // hack alert
```suggestion
                // Hack alert.
```

2020-11-08 09:50 UTC, BaronGreenback commented on MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs
> +                // hack alert
```suggestion
                // Hack alert.
```

2020-11-12 13:50 UTC, BaronGreenback approved these changes

2020-11-19 13:58 UTC, merged