Bump dependencies to Fedora 33
jellyfin/jellyfin pull request #4460
Opened 2020-11-10 21:52 UTC by yodatak

Fedora 33 is out so Fedora 31 is unmaintened so its time to migrate the build to Fedora 33 !

2020-11-11 02:14 UTC, crobibero approved these changes

2020-11-15 22:00 UTC, oddstr13 requested changes
`systemd` needs to be added to the dnf install on line 13 for this to work.

2020-11-15 23:22 UTC, yodatak commented
> `systemd` needs to be added to the dnf install on line 13 for this to work.

It install at a weak dependency in the dnf install so we don't have to specify it

2020-11-15 23:42 UTC, yodatak commented
It works when i use in my fedora 33 with podman
setenforce 0
sudo ./build -t docker -p fedora.amd64

2020-11-16 03:45 UTC, oddstr13 commented
I got an error about missing systemd dependency the first time I tried, and worked after I added explicit install of it, so not sure what's happening here then.

2020-11-17 00:05 UTC, crobibero requested changes
Can you set `ARG SDK_VERSION=5.0`? 
We've moved to dotnet5.0, and would be nice to get both changes in at the same time.

2020-11-17 02:56 UTC, oddstr13 commented
I can confirm that systemd indeed needs to be added as an explicitly installed dependency, and that whatever weak reference exists is not enough.

The build was made on a Debian buster system that had not previously built anything Jellyfin, dotnet or Fedora related.

I rebased on master before building.

<details>
<summary>Full build logs</summary>

```
oddstr13@minecraft2:~/tmp/jellyfin/jellyfin$ ./build.sh -t docker -p fedora.amd64
Sending build context to Docker daemon  9.688MB
Step 1/13 : FROM fedora:33
33: Pulling from library/fedora
ae7b613df528: Pull complete 
Digest: sha256:aa889c59fc048b597dcfab40898ee3fcaad9ed61caf12bcfef44493ee670e9df
Status: Downloaded newer image for fedora:33
 ---> b3048463dcef
Step 2/13 : ARG SOURCE_DIR=/jellyfin
 ---> Running in 68979f569fc3
Removing intermediate container 68979f569fc3
 ---> 2f416855ba18
Step 3/13 : ARG ARTIFACT_DIR=/dist
 ---> Running in 036f88692049
Removing intermediate container 036f88692049
 ---> 27dbaaa8de9d
Step 4/13 : ARG SDK_VERSION=5.0
 ---> Running in 287fa317805d
Removing intermediate container 287fa317805d
 ---> 16a2d5e1dec8
Step 5/13 : ENV SOURCE_DIR=/jellyfin
 ---> Running in 90b70e5c9378
Removing intermediate container 90b70e5c9378
 ---> 37eff706ebef
Step 6/13 : ENV ARTIFACT_DIR=/dist
 ---> Running in 958097dbd049
Removing intermediate container 958097dbd049
 ---> a4feb84700ce
Step 7/13 : ENV IS_DOCKER=YES
 ---> Running in b81a1c9e11ee
Removing intermediate container b81a1c9e11ee
 ---> c6b76fe92b61
Step 8/13 : RUN dnf update -y  && dnf install -y @buildsys-build rpmdevtools git dnf-plugins-core libcurl-devel fontconfig-devel freetype-devel openssl-devel glibc-devel libicu-devel
 ---> Running in e0b2f3fbedf3
Fedora 33 openh264 (From Cisco) - x86_64        1.6 kB/s | 2.5 kB     00:01    
Fedora Modular 33 - x86_64                      791 kB/s | 3.3 MB     00:04    
Fedora Modular 33 - x86_64 - Updates            841 kB/s | 2.4 MB     00:02    
Fedora 33 - x86_64 - Updates                    1.4 MB/s |  13 MB     00:09    
Fedora 33 - x86_64                              1.2 MB/s |  72 MB     00:59    
Dependencies resolved.
================================================================================
 Package                    Arch       Version                Repository   Size
================================================================================
Upgrading:
 glibc                      x86_64     2.32-2.fc33            updates     3.5 M
 glibc-common               x86_64     2.32-2.fc33            updates     1.8 M
 glibc-minimal-langpack     x86_64     2.32-2.fc33            updates      81 k
 libxml2                    x86_64     2.9.10-8.fc33          updates     744 k
 openssl-libs               x86_64     1:1.1.1h-1.fc33        updates     1.4 M
 pam                        x86_64     1.4.0-7.fc33           updates     559 k
 vim-minimal                x86_64     2:8.2.1961-1.fc33      updates     679 k
Installing weak dependencies:
 openssl-pkcs11             x86_64     0.4.10-7.fc33          fedora       73 k

Transaction Summary
================================================================================
Install  1 Package
Upgrade  7 Packages

Total download size: 8.9 M
Downloading Packages:
(1/8): openssl-pkcs11-0.4.10-7.fc33.x86_64.rpm   57 kB/s |  73 kB     00:01    
(2/8): glibc-minimal-langpack-2.32-2.fc33.x86_6 382 kB/s |  81 kB     00:00    
(3/8): libxml2-2.9.10-8.fc33.x86_64.rpm         457 kB/s | 744 kB     00:01    
(4/8): glibc-common-2.32-2.fc33.x86_64.rpm      541 kB/s | 1.8 MB     00:03    
(5/8): pam-1.4.0-7.fc33.x86_64.rpm              560 kB/s | 559 kB     00:00    
(6/8): openssl-libs-1.1.1h-1.fc33.x86_64.rpm    581 kB/s | 1.4 MB     00:02    
(7/8): vim-minimal-8.2.1961-1.fc33.x86_64.rpm   465 kB/s | 679 kB     00:01    
(8/8): glibc-2.32-2.fc33.x86_64.rpm             576 kB/s | 3.5 MB     00:06    
--------------------------------------------------------------------------------
Total                                           1.1 MB/s | 8.9 MB     00:08     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Upgrading        : glibc-common-2.32-2.fc33.x86_64                       1/15 
  Upgrading        : glibc-minimal-langpack-2.32-2.fc33.x86_64             2/15 
  Running scriptlet: glibc-2.32-2.fc33.x86_64                              3/15 
  Upgrading        : glibc-2.32-2.fc33.x86_64                              3/15 
  Running scriptlet: glibc-2.32-2.fc33.x86_64                              3/15 
  Upgrading        : openssl-libs-1:1.1.1h-1.fc33.x86_64                   4/15 
  Installing       : openssl-pkcs11-0.4.10-7.fc33.x86_64                   5/15 
  Upgrading        : libxml2-2.9.10-8.fc33.x86_64                          6/15 
  Upgrading        : pam-1.4.0-7.fc33.x86_64                               7/15 
  Upgrading        : vim-minimal-2:8.2.1961-1.fc33.x86_64                  8/15 
  Cleanup          : pam-1.4.0-6.fc33.x86_64                               9/15 
  Cleanup          : libxml2-2.9.10-7.fc33.x86_64                         10/15 
  Cleanup          : openssl-libs-1:1.1.1g-15.fc33.x86_64                 11/15 
  Cleanup          : vim-minimal-2:8.2.1941-1.fc33.x86_64                 12/15 
  Cleanup          : glibc-2.32-1.fc33.x86_64                             13/15 
  Cleanup          : glibc-minimal-langpack-2.32-1.fc33.x86_64            14/15 
  Cleanup          : glibc-common-2.32-1.fc33.x86_64                      15/15 
  Running scriptlet: glibc-common-2.32-1.fc33.x86_64                      15/15 
  Verifying        : openssl-pkcs11-0.4.10-7.fc33.x86_64                   1/15 
  Verifying        : glibc-2.32-2.fc33.x86_64                              2/15 
  Verifying        : glibc-2.32-1.fc33.x86_64                              3/15 
  Verifying        : glibc-common-2.32-2.fc33.x86_64                       4/15 
  Verifying        : glibc-common-2.32-1.fc33.x86_64                       5/15 
  Verifying        : glibc-minimal-langpack-2.32-2.fc33.x86_64             6/15 
  Verifying        : glibc-minimal-langpack-2.32-1.fc33.x86_64             7/15 
  Verifying        : libxml2-2.9.10-8.fc33.x86_64                          8/15 
  Verifying        : libxml2-2.9.10-7.fc33.x86_64                          9/15 
  Verifying        : openssl-libs-1:1.1.1h-1.fc33.x86_64                  10/15 
  Verifying        : openssl-libs-1:1.1.1g-15.fc33.x86_64                 11/15 
  Verifying        : pam-1.4.0-7.fc33.x86_64                              12/15 
  Verifying        : pam-1.4.0-6.fc33.x86_64                              13/15 
  Verifying        : vim-minimal-2:8.2.1961-1.fc33.x86_64                 14/15 
  Verifying        : vim-minimal-2:8.2.1941-1.fc33.x86_64                 15/15 

Upgraded:
  glibc-2.32-2.fc33.x86_64                    glibc-common-2.32-2.fc33.x86_64  
  glibc-minimal-langpack-2.32-2.fc33.x86_64   libxml2-2.9.10-8.fc33.x86_64     
  openssl-libs-1:1.1.1h-1.fc33.x86_64         pam-1.4.0-7.fc33.x86_64          
  vim-minimal-2:8.2.1961-1.fc33.x86_64       

Installed:
  openssl-pkcs11-0.4.10-7.fc33.x86_64                                           

Complete!
Last metadata expiration check: 0:01:08 ago on Tue Nov 17 02:12:55 2020.
Dependencies resolved.
===========================================================================================
 Package                      Arch    Version                                Repo      Size
===========================================================================================
Installing:
 dnf-plugins-core             noarch  4.0.18-1.fc33                          updates   34 k
 fontconfig-devel             x86_64  2.13.92-12.fc33                        fedora   129 k
 freetype-devel               x86_64  2.10.4-1.fc33                          updates  1.1 M
 git              [...]

2020-11-17 02:56 UTC, oddstr13 approved these changes

2020-11-17 02:58 UTC, crobibero approved these changes

2020-11-17 03:03 UTC, merged