[Fix] Test query value
jellyfin/jellyfin pull request #4589
Opened 2020-11-25 23:06 UTC by ConfusedPolarBear

**Changes**
`GetWhereClauses()` only checked if several query values were present, instead of their values.

**Issues**
Fixes #4578

2020-11-26 09:40 UTC, BaronGreenback commented on Emby.Server.Implementations/Data/SqliteItemRepository.cs
> +            if (query.HasImdbId.HasValue && query.HasImdbId.Value)
An alternative is

```suggestion
            if (query.HasImdbId == true)
```

This may be slightly more optimized.

2020-11-26 09:47 UTC, BaronGreenback approved these changes
Personally i prefer 
```
if (query.HasXXXX == true)
```
but that's a matter of style and this will work.

2020-11-26 13:09 UTC, cvium commented on Emby.Server.Implementations/Data/SqliteItemRepository.cs
> +            if (query.HasImdbId.HasValue && query.HasImdbId.Value)
What about the case where it's false? Shouldn't it be `"ProviderIds not like '%imdb=%'"` then?

2020-11-27 00:07 UTC, BaronGreenback reviewed
.

2020-11-27 00:08 UTC, BaronGreenback requested changes
Cvium is right.

2020-11-27 22:46 UTC, crobibero approved these changes

2020-11-28 12:05 UTC, cvium approved these changes

2020-11-29 12:52 UTC, Mange commented
Looks great IMO!

2020-12-02 14:04 UTC, BaronGreenback approved these changes

2020-12-02 14:55 UTC, merged