change default webdir config from option to env var
jellyfin/jellyfin pull request #5087
Opened 2021-01-23 18:22 UTC by heylix

While using systemd to start jellyfin.service on Fedora 33,
the service failed. After inspecting the logs, the following
output seemed relevant:

[INF] [1] Main: Web resources path: /usr/lib64/jellyfin/jellyfin-web
[…]
System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib64/jellyfin/jellyfin-web. […]

Apparently the option doesn't get picked up by the unitfile
present if there's been an older version of jellyfin installed
(see fedora/jellyfin.service line 8).

After changing the corresponding environment variable to be
consistent in handling with the rest of the env variables in
/etc/sysconfig/jellyfin, the server starts without a hitch.

Changed the default config file for Debian, too, so both
distributions have the same default values.

**Changes**

**Issues**

2021-01-24 00:37 UTC, crobibero approved these changes

2021-01-27 08:10 UTC, Ullmie02 approved these changes

2021-02-08 14:34 UTC, joshuaboniface commented
First thing's first, everything is already consistent in Debian, let's not change that.

Second, I'm thinking this is a misconfiguration in the jellyfin-web RPM spec, not in here. The web fils *should* be installed to `/usr/lib[64]/jellyfin/web` like on Debian, but I don't understand RPM spec files enough to see where that's happening (and it looks to not be the case, there's a `jellyfin-web` bit in there). Can you confirm where the web files are actually installed on your system?

The opt should 100% be working, since it's loaded as-is in the ExecStart line of the service unit:

```
ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ...
```

Changing it to an envvar won't fix things if it's pointing at the wrong place.

I also assume this is for 10.7.0 RC3? Or is this for a previous stable version?

2021-02-08 14:35 UTC, joshuaboniface requested changes
See above.

2021-06-30 07:59 UTC, closed without merging