Replaced /d with [0-9], see issue #2923
jellyfin/jellyfin pull request #5142
Opened 2021-02-01 02:56 UTC by M0ssTee

**Changes**
Replaced /d with [0-9] in all jellyfin/jellyfin files

**Issues**
#2923

2021-02-01 14:34 UTC, crobibero requested changes

2021-02-01 14:34 UTC, crobibero commented on Emby.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunManager.cs
> +            var regExp = new Regex(@"\/ch([0-9]+)-?([[0-9]*)");
```suggestion
            var regExp = new Regex(@"\/ch([0-9]+)-?([0-9]*)");
```

2021-02-04 14:30 UTC, crobibero commented on MediaBrowser.MediaEncoding/Subtitles/AssParser.cs
> +                    subEvent.Text = Regex.Replace(subEvent.Text, @"\{(\\[\w]+\(?([\w[0-9]]+,?)+\)?)+\}", string.Empty, RegexOptions.IgnoreCase);
```suggestion
                    subEvent.Text = Regex.Replace(subEvent.Text, @"\{(\\[\w]+\(?([\w0-9]+,?)+\)?)+\}", string.Empty, RegexOptions.IgnoreCase);
```

2021-02-04 21:16 UTC, crobibero approved these changes

2021-02-07 14:24 UTC, Ullmie02 approved these changes

2021-02-08 13:52 UTC, merged