make sure network path substitution matches correctly
jellyfin/jellyfin pull request #5381
Opened 2021-03-05 13:10 UTC by cvium

Fixes #5313

2021-03-05 14:34 UTC, crobibero approved these changes

2021-03-05 20:31 UTC, BaronGreenback approved these changes

2021-03-05 20:31 UTC, BaronGreenback commented on Emby.Server.Implementations/Library/PathExtensions.cs
> +            }
Couldn't this just be a _replace_?

```
            newSubPath = newSubPath.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
```

2021-03-05 20:31 UTC, BaronGreenback commented on Emby.Server.Implementations/Library/PathExtensions.cs
> +            return true;
Would this be more optimised, as I would expect _equals_ to be faster than _contains_ ???
```
            newPath = path.Replace(subPath, newSubPath, StringComparison.OrdinalIgnoreCase);
            return !string.Equals(newPath, path, StringComparison.OrdinalIgnoreCase);
```

2021-03-06 00:34 UTC, Bond-009 requested changes
With less checks and allocations:
(probably missed some corner cases)
```cs
diff --git a/Emby.Server.Implementations/Library/PathExtensions.cs b/Emby.Server.Implementations/Library/PathExtensions.cs
index 1fc5526ae1..ad84350171 100644
--- a/Emby.Server.Implementations/Library/PathExtensions.cs
+++ b/Emby.Server.Implementations/Library/PathExtensions.cs
@@ -1,6 +1,7 @@
 #nullable enable
 
 using System;
+using System.IO;
 using System.Diagnostics.CodeAnalysis;
 using System.Text.RegularExpressions;
 
@@ -60,19 +61,17 @@ namespace Emby.Server.Implementations.Library
         /// <exception cref="ArgumentNullException"><paramref name="path" />, <paramref name="newSubPath" /> or <paramref name="newSubPath" /> is empty.</exception>
         public static bool TryReplaceSubPath(this string path, string subPath, string newSubPath, [NotNullWhen(true)] out string? newPath)
         {
-            if (string.IsNullOrWhiteSpace(path))
-            {
-                throw new ArgumentNullException(nameof(path));
-            }
+            newPath = null;
 
-            if (string.IsNullOrWhiteSpace(subPath))
+            int subLen = subPath.Length;
+            if (path.Length == 0 || subLen == 0 || newSubPath.Length == 0)
             {
-                throw new ArgumentNullException(nameof(subPath));
+                return false;
             }
 
-            if (string.IsNullOrWhiteSpace(newSubPath))
+            if (subLen > path.Length)
             {
-                throw new ArgumentNullException(nameof(newSubPath));
+                return false;
             }
 
             char oldDirectorySeparatorChar;
@@ -91,40 +90,18 @@ namespace Emby.Server.Implementations.Library
                 newDirectorySeparatorChar = '\\';
             }
 
-            if (path.Contains(oldDirectorySeparatorChar, StringComparison.Ordinal))
-            {
-                path = path.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
-            }
-
-            if (subPath.Contains(oldDirectorySeparatorChar, StringComparison.Ordinal))
-            {
-                subPath = subPath.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
-            }
+            path = path.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
+            subPath = subPath.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
 
             // We have to ensure that the sub path ends with a directory separator otherwise we'll get weird results
             // when the sub path matches a similar but in-complete subpath
-            if (!subPath.EndsWith(newDirectorySeparatorChar))
-            {
-                subPath += newDirectorySeparatorChar;
-            }
-
-            if (newSubPath.Contains(oldDirectorySeparatorChar, StringComparison.Ordinal))
-            {
-                newSubPath = newSubPath.Replace(oldDirectorySeparatorChar, newDirectorySeparatorChar);
-            }
-
-            if (!newSubPath.EndsWith(newDirectorySeparatorChar))
-            {
-                newSubPath += newDirectorySeparatorChar;
-            }
-
-            if (!path.Contains(subPath, StringComparison.OrdinalIgnoreCase))
+            if (!path.StartsWith(subPath, StringComparison.OrdinalIgnoreCase)
+                || (subPath[^1] != newDirectorySeparatorChar && path[subPath.Length] != newDirectorySeparatorChar))
             {
-                newPath = null;
                 return false;
             }
 
-            newPath = path.Replace(subPath, newSubPath, StringComparison.OrdinalIgnoreCase);
+            newPath = Path.Join(newSubPath, path.AsSpan(subPath.Length));
             return true;
         }
     }
```

2021-03-06 00:34 UTC, Bond-009 commented on Emby.Server.Implementations/Library/PathExtensions.cs
> +            }
Isn't the whole point of a `Try` method that it fails gracefully?

2021-03-06 20:14 UTC, Bond-009 requested changes
Last nitpick (I think)

2021-03-06 20:14 UTC, Bond-009 commented on Emby.Server.Implementations/Library/LibraryManager.cs
>              if (!string.IsNullOrWhiteSpace(metadataPath) && !string.IsNullOrWhiteSpace(metadataNetworkPath))
Same

2021-03-06 20:38 UTC, Bond-009 approved these changes

2021-03-06 20:38 UTC, merged