FxCop -> Net Analyzers (part 2)
jellyfin/jellyfin pull request #5422
Opened 2021-03-09 04:58 UTC by Bond-009

2021-03-09 13:13 UTC, barronpm approved these changes

2021-03-09 15:24 UTC, crobibero requested changes

2021-03-09 15:24 UTC, crobibero commented on Jellyfin.Data/DayOfWeekHelper.cs
> +                DynamicDayOfWeek.Weekday => new[] { DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday },
```suggestion
                DynamicDayOfWeek.Weekday => new[] { DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday },
```

2021-03-09 16:02 UTC, crobibero approved these changes

2021-03-09 19:21 UTC, h1dden-da3m0n commented on Jellyfin.Data/DayOfWeekHelper.cs
> +                DynamicDayOfWeek.Everyday => new[] { DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday, DayOfWeek.Saturday, DayOfWeek.Su
was Sunday placed in this statement twice on purpose? (once before Monday and once on the end after Saturday)

2021-03-09 19:31 UTC, h1dden-da3m0n commented on Jellyfin.Data/DayOfWeekHelper.cs
> +                DynamicDayOfWeek.Everyday => new[] { DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday, DayOfWeek.Saturday, DayOfWeek.Su
I see, and yeah I noticed this in some other context but failed to connect the dots. Thank you for the clarification :wink:

2021-03-11 21:22 UTC, Bond-009 commented on MediaBrowser.Common/Json/JsonDefaults.cs
> +        public static JsonSerializerOptions Options
yep

2021-03-13 20:56 UTC, crobibero approved these changes

2021-03-13 23:37 UTC, MrTimscampi commented on Jellyfin.Data/DayOfWeekHelper.cs
> -                DynamicDayOfWeek.Weekday => new[] { DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday },
Sunday being a weekend or not is very culture dependent. Not sure if it should be hardcoded or not.

2021-03-13 23:41 UTC, merged