Fix network test on dns failure
jellyfin/jellyfin pull request #5762
Opened 2021-04-10 18:45 UTC by BaronGreenback

Test shouldn't now fail in the case of dns resolution failure.

2021-04-11 16:05 UTC, crobibero approved these changes

2021-04-12 06:42 UTC, oddstr13 requested changes

2021-04-12 06:42 UTC, oddstr13 commented on tests/Jellyfin.Networking.Tests/NetworkParseTests.cs
> +        [InlineData("ospoakdposkd.abc", "", false, "eth11")]
```suggestion
        // https://en.wikipedia.org/wiki/.test
        [InlineData("invalid.domain.test", "", false, "eth11")]
```

2021-04-12 10:49 UTC, oddstr13 approved these changes

2021-05-05 04:10 UTC, merged