Change repeated library names generator
jellyfin/jellyfin pull request #5823
Opened 2021-04-15 11:24 UTC by danieladov

In the current implementation, if a library with a repeated name is created, a 1 will be add at the end of the string (movies,movies1) but if another one is created another 1 is added (movies, movies1, and movies11).

With my implementation, the last number is incremented each time a new library with a repeated name is created (movies, movies1, and movies2). The counter will work up to 19 which I think is good enough.

2021-04-18 15:14 UTC, Ullmie02 approved these changes

2021-04-18 15:57 UTC, crobibero approved these changes

2021-04-18 17:03 UTC, cvium requested changes
"Works up to 19" seems like a half measure. The current implementation is silly but it's consistent.

2021-04-20 17:02 UTC, danieladov commented
> "Works up to 19" seems like a half measure. The current implementation is silly but it's consistent.

Yeah, you are right, but I didn't found any better "easy to implement" solution. Right now if you create 20 libraries named "movies", the las one would be movies1111111111111111111 which is consistent, but practical?
Do you have any idea on how to do it?

2021-12-20 14:25 UTC, crobibero commented
Closing in favor of https://github.com/jellyfin/jellyfin/pull/7013

2021-12-20 14:25 UTC, closed without merging