Code Clean up: "value assigned is not used in any execution path"
jellyfin/jellyfin pull request #5836
Opened 2021-04-17 08:29 UTC by BaronGreenback

Identified by ReSharper. Removed all unneccessary "value assigned is not used in any execution path".

2021-04-19 08:16 UTC, Ullmie02 requested changes
Don't like the commented out code. I would prefer if they were removed or explained why they are commented out.

2021-04-19 09:23 UTC, BaronGreenback commented
> Don't like the commented out code. I would prefer if they were removed or explained why they are commented out.



> Don't like the commented out code. I would prefer if they were removed or explained why they are commented out.

Removed.

2021-04-19 19:32 UTC, Ullmie02 approved these changes

2021-05-08 16:25 UTC, crobibero approved these changes

2021-12-24 02:42 UTC, crobibero commented on Jellyfin.Api/Controllers/VideoHlsController.cs
> +                if (isWindows)
```suggestion
                if (OperatingSystem.IsWindows())
```

2021-12-24 02:43 UTC, crobibero approved these changes

2021-12-24 02:43 UTC, merged