Fix ArgumentOutOfRangeException when getting PostedPlaybackInfo
jellyfin/jellyfin pull request #5864
Opened 2021-04-19 12:39 UTC by DeeJayBro

MediaInfoController.GetPostedPlaybackInfo method attempts to access the first item of the mediaInfo Array without checking if MediaInfoHelper.GetPlaybackInfo returned an ErrorCode

**Changes**
Skip Code that accesses mediaInfo MediaSources Array when an ErrorCode is returned

2021-04-19 12:49 UTC, crobibero reviewed
I’m not sure what the clients are expecting, but if we aren’t sending a successful playback info response I would expect a 400 status code 

@jellyfin/client

2021-06-20 09:44 UTC, DeeJayBro commented
As far as i see it, the web doesn't handle the 400 return  correctly, but correctly displays an error message with "NoCompatibleStream" when my change is implemented

2021-06-20 13:03 UTC, crobibero approved these changes

2021-07-11 20:57 UTC, Bond-009 requested changes

2021-07-11 20:57 UTC, Bond-009 commented on Jellyfin.Api/Controllers/MediaInfoController.cs
> +            if (info.ErrorCode != null)
Why here instead of line 163?

2021-07-16 09:42 UTC, DeeJayBro commented on Jellyfin.Api/Controllers/MediaInfoController.cs
> +            if (info.ErrorCode != null)
Sounds good, will change!

2021-07-17 18:53 UTC, Bond-009 approved these changes

2021-07-17 18:54 UTC, merged