Reduce some allocations
jellyfin/jellyfin pull request #6054
Opened 2021-05-16 12:50 UTC by cvium

**Changes**
Reduce allocations by using spans and by reducing the number of times a column value is retrieved (effectively halved).

2021-05-16 13:21 UTC, crobibero commented on Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs
> +                && name.Equals("Emby", StringComparison.OrdinalIgnoreCase))
```suggestion
                && !name.Equals("Emby", StringComparison.OrdinalIgnoreCase))
```

Missed conditional?

2021-05-16 13:27 UTC, cvium commented on Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs
> +                && name.Equals("Emby", StringComparison.OrdinalIgnoreCase))
True

2021-05-17 13:22 UTC, crobibero approved these changes

2021-05-18 22:03 UTC, Bond-009 requested changes

2021-05-18 22:03 UTC, Bond-009 commented on tests/Jellyfin.Providers.Tests/MediaInfo/SubtitleResolverTests.cs
> +        public void AddExternalSubtitleStreams_GivenMixedFilenames_ReturnsValidSubtitles(List<MediaStream> streams, string videoPath, int startIndex, string[] files, List<MediaStream> expectedResult)
Doesn't an array make more sense for `expectedResult`?

2021-05-19 12:31 UTC, Bond-009 requested changes

2021-05-19 12:31 UTC, Bond-009 commented on Emby.Server.Implementations/Data/SqliteExtensions.cs
>          }
These also shouldn't be nullable

2021-05-19 12:31 UTC, Bond-009 commented on Emby.Server.Implementations/Data/SqliteExtensions.cs
> +            return true;
Remove the `[NotNullWhen(true)]`

2021-05-20 20:36 UTC, Bond-009 approved these changes

2021-05-20 20:40 UTC, merged