Added ConfigurationChanging event to plugin class.
jellyfin/jellyfin pull request #6069
Opened 2021-05-17 22:24 UTC by BaronGreenback

Added ConfigurationChanging that gets called just prior to plugin configuration saving.

This enables the configuration to be validated prior to saving, stopping the need for it to be validated and saved a second time.

2021-05-18 00:41 UTC, crobibero approved these changes

2021-05-18 08:20 UTC, Ullmie02 approved these changes

2021-07-11 21:01 UTC, Bond-009 commented
Not sure if the is what we want to verify plugin configurations.
Maybe a `IHasConfigurationValidation` interface that we can check for just like `IHasPluginConfiguration` would be better?

2021-07-11 21:02 UTC, Bond-009 requested changes
See above comment

2022-01-19 13:17 UTC, crobibero commented
See https://github.com/jellyfin/jellyfin/pull/7045

2022-01-19 13:17 UTC, closed without merging