Fix duplicate keys causing an exception
jellyfin/jellyfin pull request #6165
Opened 2021-06-08 20:28 UTC by Bond-009

2021-06-08 20:30 UTC, BaronGreenback approved these changes

2021-06-08 21:56 UTC, crobibero approved these changes

2021-06-09 06:58 UTC, cvium requested changes

2021-06-09 06:58 UTC, cvium commented on Jellyfin.Server/Middleware/UrlDecodeQueryFeature.cs
> +                    pairs.TryAdd(pair[..i].ToString(), new StringValues(pair[(i + 1)..].ToString()));
This breaks array modelbinding. StringValues are unfortunately readonly though.

2021-06-09 08:04 UTC, cvium approved these changes

2021-06-09 08:23 UTC, merged