Use artist backdrop for generated library image
jellyfin/jellyfin pull request #6257
Opened 2021-07-03 00:52 UTC by MrTimscampi

**Changes**

Use the artist backdrop for music library images, instead of the primary image of the album.

Before
![image](https://user-images.githubusercontent.com/19396809/124338688-9e7ed400-dba9-11eb-96f0-ac490fd10ca7.png)
After
![image](https://user-images.githubusercontent.com/19396809/124338693-a63e7880-dba9-11eb-8f13-46c090b1b9c9.png)

Rider also complained about paintColor and textPaint not being properly disposed, so I added that too.

**Issues**

2021-07-05 17:12 UTC, Bond-009 requested changes

2021-07-05 17:12 UTC, Bond-009 commented on Jellyfin.Drawing.Skia/StripCollageBuilder.cs
> +            textPaint.Dispose();
Use using statements instead

2021-07-07 00:26 UTC, crobibero approved these changes

2021-07-09 18:35 UTC, barronpm approved these changes

2021-08-15 17:57 UTC, Bond-009 approved these changes

2021-09-05 17:30 UTC, merged