Add OpenAPI workflow
jellyfin/jellyfin pull request #6308
Opened 2021-07-17 09:00 UTC by nielsvanvelzen

**Changes**
Add a new workflow called that does the following things:
- Generate OpenAPI spec for master branch
  - although already available via azure on repo.jellyfin.org, this adds it the the GitHub interface
- Generate OpenAPI spec for master branch
  - Useful when I need to test something with the Kotlin SDK, or to inspect changes in the file
- Calculate difference between PR spec and baseline (target branch) spec using [openapi-diff](https://github.com/OpenAPITools/openapi-diff)
  - Diff is rendered using markdown and added as a comment to the PR
  - If the PR is updated it will update the existing comment
  - Comment uses a `<details>` element to prevent skyscraper tall comments
    - For example, when updating BaseItemDto

The comments will help reviewers to determine if a PR contains breaking API changes, which might not be easy to notice in the code reviews.

**To do**
Some work left for this PR that I need some help with:

- Need to use `pull_request_target` instead of `pull_request` BUT this would allow a malicious actor to expose secrets by making changes to the .NET code. No idea how to fix.
  - Need to use jellyfin-bot for comment
- Detect the commit of the base branch the head branch is based on to use as a baseline to prevent changes made in the API in base showing up in the diff.
  - example: property removed from baseitemdto in master would also show up in this PR if the change wasn't in master when this branch was created.
**Issues**

**Example**
See my personal fork for an example of this workflow: https://github.com/nielsvanvelzen/jellyfin/pull/91

**Issues**

2021-07-22 19:29 UTC, nielsvanvelzen commented
I'm marking the PR as ready now since it does work, the "to do" list contains 2 items that should be considered before merging though.

2021-07-29 16:12 UTC, ferferga commented
The ``pull_request_target`` event checkouts code from the base branch instead [(that's what I understand from docs)](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).

However, for extra peace of mind, why not run this on master commits?

2021-07-29 16:43 UTC, nielsvanvelzen commented
> However, for extra peace of mind, why not run this on master commits?

We need the openapi.json file for both the PR branch and the target (=master) branch to compare.

2021-08-01 16:21 UTC, crobibero approved these changes

2021-11-02 08:43 UTC, cvium requested changes

2021-11-02 08:43 UTC, cvium commented on .github/workflows/openapi.yml
> +        uses: actions/setup-dotnet@v1
Change to
```
    dotnet-version: '6.0.x'
    include-prerelease: true
```

2021-11-02 18:43 UTC, cvium approved these changes

2021-11-02 18:43 UTC, merged