Fix analysis issues
jellyfin/jellyfin pull request #6335
Opened 2021-07-23 00:36 UTC by richlander

Resolves all analysis issues for MediaBrowsers.Providers project.

Supports https://github.com/jellyfin/jellyfin/issues/2149

2021-07-23 01:19 UTC, crobibero commented
Thank you for the PR. If you continue making these fixes, please split the PR up into parts so reviewing is easier

2021-07-23 01:30 UTC, richlander commented
How would you like me to do that? Like 20 fixes at a time or number of files?

2021-07-23 01:34 UTC, crobibero commented
How I typically organize it is to remove x number of warnings, each warning in a commit

see https://github.com/jellyfin/jellyfin/pull/6281 for example

2021-07-23 01:36 UTC, richlander commented
Oh, I see. I never thought about doing it that way.

I see I have 24 more errors to fix for the build to pass. If it's OK, I'll do fix those, and then switch to your approach for the next one.

2021-07-23 01:43 UTC, crobibero commented
That works for me, thanks again

2021-07-23 18:48 UTC, crobibero approved these changes

2021-07-26 14:07 UTC, barronpm approved these changes

2021-08-06 15:36 UTC, Bond-009 requested changes

2021-08-06 15:36 UTC, Bond-009 commented on MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
> +        /// <summary>Dispose method.</summary>
Same

2021-08-06 15:36 UTC, Bond-009 commented on MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs
> +        /// <param name="disposing">Specify true to dispose.</param>
```suggestion
/// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
```

2021-08-06 15:36 UTC, Bond-009 commented on MediaBrowser.Providers/Subtitles/SubtitleManager.cs
> +#pragma warning disable CA1508
Maybe add a note that this is a bug in the analyzer?
Could also add a ref
https://github.com/dotnet/roslyn-analyzers/issues/5160

2021-08-10 02:51 UTC, richlander commented
I believe I resolved the outstanding feedback. Thanks!

2021-08-13 15:56 UTC, Bond-009 approved these changes

2021-08-13 15:56 UTC, merged