Add 'includeAdult' option for TheMovieDb
jellyfin/jellyfin pull request #6457
Opened 2021-08-21 12:10 UTC by Izumiko

**Changes**
Some TV shows and movies are labeled as 'adult' at TheMovieDb. The TMDbLib uses the 'includeAdult' parameter to show this content in search results. This PR adds a configuration option to support this feature.

2021-08-21 13:27 UTC, crobibero approved these changes

2021-08-21 14:04 UTC, Bond-009 requested changes

2021-08-21 14:04 UTC, Bond-009 commented on MediaBrowser.Providers/Plugins/Tmdb/Configuration/PluginConfiguration.cs
> +#pragma warning disable CS1591
Please add documentation to new files.

2021-08-21 14:04 UTC, Bond-009 commented on MediaBrowser.Providers/Plugins/Tmdb/Plugin.cs
> +#pragma warning disable CS1591
Same

2021-08-21 15:42 UTC, Izumiko commented
It is better to add this option to the library level, not to global. But I didn't find a proper way to achieve this due to my limited knowledge. So I added it to the plugin configuration page for now.

2021-09-11 12:20 UTC, Bond-009 approved these changes

2021-09-11 21:00 UTC, merged