FIX: cannot compare bitstream of different video codec
jellyfin/jellyfin pull request #6617
Opened 2021-09-26 18:31 UTC by koying

**Changes**

It doesn't really make sense to compare bitstream rate of 2 different codec.
Not downscaling because, e.g., a hevc 9Mb/s is lower than a h264 10Mb/s is comparing pears and apples.

Partial revert of https://github.com/jellyfin/jellyfin/pull/4432

**Issues**

2022-09-13 22:49 UTC, Bond-009 approved these changes
This makes sense, I think?

2022-09-14 06:23 UTC, cvium approved these changes

2022-09-14 07:26 UTC, nyanmisaka requested changes
https://github.com/jellyfin/jellyfin/blob/d75c699ad4568fb2546588497c201fd6e4830477/MediaBrowser.Model/Dlna/ResolutionNormalizer.cs#L28-L39

Normalize() is used to downscale the resolution according to the hardcoded ResolutionConfigurations instead of checking the codecs, which is not reliable in some cases.

e.g. removing this will cause H.264 High10 1080p 4M video to be transcoded to H.264 720p 4M if the video resolution is not requested and the target bitrate is set to 4M. Downscaling is pointless in this case.

2022-09-14 17:51 UTC, Bond-009 commented
Closing, see comment above

2022-09-14 17:51 UTC, closed without merging