Update LocalizationManager.cs
jellyfin/jellyfin pull request #6839
Opened 2021-11-13 17:17 UTC by WWWesten

Synchronize language names list with jelliyfin-web and language codes in list with language resource file names

**Changes**

**Issues**

2021-11-13 17:19 UTC, WWWesten commented
Related to https://github.com/jellyfin/jellyfin-web/pull/3171

2021-11-14 00:06 UTC, crobibero approved these changes

2021-11-16 12:34 UTC, WWWesten commented
@cvium Can You take a moment and review the code?

2021-11-18 07:51 UTC, cvium approved these changes

2021-11-18 10:11 UTC, WWWesten commented
Hi @joshuaboniface, can You take a look and merge PR? Thanks.

2021-11-18 13:55 UTC, Bond-009 requested changes

2021-11-18 13:55 UTC, Bond-009 commented on Emby.Server.Implementations/Localization/LocalizationManager.cs
> +            yield return new LocalizationOption("Afrikaans (af)", "af");
Why the ` (af)` here?

2021-11-18 14:17 UTC, WWWesten commented on Emby.Server.Implementations/Localization/LocalizationManager.cs
> +            yield return new LocalizationOption("Afrikaans (af)", "af");
Ooops!

2021-11-19 17:00 UTC, Bond-009 approved these changes

2021-11-19 17:00 UTC, merged