Providermanager cleanup
jellyfin/jellyfin pull request #7039
Opened 2021-12-23 22:17 UTC by 1337joe

A bunch of incremental improvements to ProviderManager.cs and related files, primarily focusing on `RefreshSingleItem`, `GetImageProviders`, and `GetMetadataProviders`.

**Changes**
- Pulled a couple public methods up to the interface, resolved `#nullable disable`, general minor cleanup
- Stored library type options and fetcher order logic up front instead of rechecking multiple times for each provider
- Merged and simplified similar/duplicated code for image and metadata sorting
- Added unit tests

2021-12-24 01:56 UTC, crobibero commented on MediaBrowser.Providers/Manager/ProviderManager.cs
> +                })
```suggestion
                    // local and remote providers will be interleaved in the final order
                    // only relative order within a type matters: consumers of the list filter to one or the other
                    i switch
                    {
                        ILocalMetadataProvider => GetConfiguredOrder(localMetadataReaderOrder, i.Name),
                        IRemoteMetadataProvider => GetConfiguredOrder(metadataFetcherOrder, i.Name),
                        // Default to end
                        _ => int.MaxValue
                    })
```

2021-12-24 21:20 UTC, crobibero commented
@jellyfin-bot rebase

2021-12-25 19:11 UTC, crobibero approved these changes

2022-01-15 19:39 UTC, cvium commented on tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
> +                }
```suggestion
                var times = i == expectedIndex ? Times.Once() : Times.Never();
                servicesList[i].Verify(mock => mock.RefreshMetadata(It.IsAny<BaseItem>(), It.IsAny<MetadataRefreshOptions>(), It.IsAny<CancellationToken>()), times);
```

2022-10-07 10:31 UTC, cvium approved these changes

2022-11-23 13:03 UTC, Bond-009 requested changes
This should fix the failing tests

2022-11-23 13:03 UTC, Bond-009 commented on tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
> +        private static TheoryData<Mock<IMetadataService>[], int> RefreshSingleItemOrderData()
```suggestion
        public static TheoryData<Mock<IMetadataService>[], int> RefreshSingleItemOrderData()
```

2022-11-23 13:03 UTC, Bond-009 commented on tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
> +            Assert.Equal(expectedResult, actual.Result);
```suggestion
        public async Task RefreshSingleItem_ServiceOrdering_FollowsPriority(Mock<IMetadataService>[] servicesList, int expectedIndex)
        {
            var item = new Movie();

            using var providerManager = GetProviderManager();
            AddParts(providerManager, metadataServices: servicesList.Select(s => s.Object).ToArray());

            var refreshOptions = new MetadataRefreshOptions(Mock.Of<IDirectoryService>(MockBehavior.Strict));
            var actual = await providerManager.RefreshSingleItem(item, refreshOptions, CancellationToken.None).ConfigureAwait(false);

            Assert.Equal(ItemUpdateType.MetadataDownload, actual);
            for (var i = 0; i < servicesList.Length; i++)
            {
                var times = i == expectedIndex ? Times.Once() : Times.Never();
                servicesList[i].Verify(mock => mock.RefreshMetadata(It.IsAny<BaseItem>(), It.IsAny<MetadataRefreshOptions>(), It.IsAny<CancellationToken>()), times);
            }
        }

        [Theory]
        [InlineData(true)]
        [InlineData(false)]
        public async Task RefreshSingleItem_RefreshMetadata_WhenServiceFound(bool serviceFound)
        {
            var item = new Movie();

            var servicesList = new[] { MockIMetadataService(false, serviceFound) };

            using var providerManager = GetProviderManager();
            AddParts(providerManager, metadataServices: servicesList.Select(s => s.Object).ToArray());

            var refreshOptions = new MetadataRefreshOptions(Mock.Of<IDirectoryService>(MockBehavior.Strict));
            var actual = await providerManager.RefreshSingleItem(item, refreshOptions, CancellationToken.None).ConfigureAwait(false);

            var expectedResult = serviceFound ? ItemUpdateType.MetadataDownload : ItemUpdateType.None;
            Assert.Equal(expectedResult, actual);
```

2022-11-23 13:03 UTC, Bond-009 commented on tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
> +        private static TheoryData<int, int[]?, int[]?, int?[]?, int[]> GetImageProvidersOrderData()
```suggestion
        public static TheoryData<int, int[]?, int[]?, int?[]?, int[]> GetImageProvidersOrderData()
```

2022-11-23 13:03 UTC, Bond-009 commented on tests/Jellyfin.Providers.Tests/Manager/ProviderManagerTests.cs
> +        private static TheoryData<string[], int[]?, int[]?, int[]?, int[]?, int?[]?, int[]> GetMetadataProvidersOrderData()
```suggestion
        public static TheoryData<string[], int[]?, int[]?, int[]?, int[]?, int?[]?, int[]> GetMetadataProvidersOrderData()
```

2022-11-23 15:27 UTC, 1337joe commented
> This should fix the failing tests

Thanks, I somehow missed that tests were failing after the merge from master.

2022-11-23 17:23 UTC, Bond-009 approved these changes

2022-11-23 17:24 UTC, merged

2023-03-31 00:59 UTC, IDisposable commented
Just FYI, if building from current sources and running with external plug-ins that were compiled against the OLD `IBaseItemManager` interface, the plug-ins will throw `MissingMethodExceptions` and fail. 

I am not sure that's supposed to be a supported scenario, but adding the original methods back to the interface and implementing shim methods in the `BaseItemManager` class to "do the right thing" seems to make the plug-ins continue to function.

Just added back the old methods in the interface , and then added these forwarders.
```csharp
/// <inheritdoc />
public bool IsMetadataFetcherEnabled(BaseItem baseItem, LibraryOptions libraryOptions, string name)
{
    // just upcall into the by-TypeOptions version using the logic the old path would have used
    TypeOptions libraryTypeOptions = libraryOptions?.GetTypeOptions(baseItem.GetType().Name);
    return this.IsMetadataFetcherEnabled(baseItem, libraryTypeOptions, name);
}

/// <inheritdoc />
public bool IsImageFetcherEnabled(BaseItem baseItem, LibraryOptions libraryOptions, string name)
{
    // just upcall into the by-TypeOptions version using the logic the old path would have used
    TypeOptions libraryTypeOptions = libraryOptions?.GetTypeOptions(baseItem.GetType().Name);
    return this.IsImageFetcherEnabled(baseItem, libraryTypeOptions, name);
}
```

2023-03-31 01:25 UTC, IDisposable commented
PR #9566 submitted to restore the old methods (as shims to the new ones)