[Bugfix] Provile bitStreamArgs for HLS fMP4
jellyfin/jellyfin pull request #7333
Opened 2022-02-18 13:20 UTC by eyezak

Fix audio sync in HLS fMP4

**Changes**
Provide audio bitstream arguments to ffmpeg for both ts and fMP4 HLS streaming

2022-02-19 14:43 UTC, crobibero commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                && !state.SupportedVideoCodecs.Contains(videoStream.Codec, StringComparison.OrdinalIgnoreCase)))
```suggestion
            if (string.IsNullOrEmpty(videoStream.Codec)
                || (state.SupportedVideoCodecs.Length != 0
                    && !state.SupportedVideoCodecs.Contains(videoStream.Codec, StringComparison.OrdinalIgnoreCase)))
```

2022-02-21 15:20 UTC, crobibero approved these changes

2022-02-21 15:40 UTC, nyanmisaka commented
Does `-bsf:a aac_adtstoasc` work on source video containers other than MPEG-TS?

2022-02-23 14:27 UTC, eyezak commented
> Does `-bsf:a aac_adtstoasc` work on source video containers other than MPEG-TS?

It definitely applies to raw aac files as well. I can rework this change to look at source files instead of output, if that is correct here

2022-03-11 06:28 UTC, nyanmisaka commented
> It definitely applies to raw aac files as well. I can rework this change to look at source files instead of output, if that is correct here

That make sense. It should be applied when mediaSourceContainer is aac.

2022-03-22 23:41 UTC, Shadowghost commented
What's the state on this?

2022-03-25 13:55 UTC, joshuaboniface approved these changes

2022-03-25 14:09 UTC, nyanmisaka requested changes

2022-03-25 14:09 UTC, nyanmisaka commented on Jellyfin.Api/Controllers/DynamicHlsController.cs
> +                    var bitStreamArgs = EncodingHelper.GetAudioBitStreamArguments(state, state.Request.SegmentContainer, state.MediaSource.Container, state.TranscodingType);
```suggestion
                    var bitStreamArgs = EncodingHelper.GetAudioBitStreamArguments(state, state.Request.SegmentContainer, state.MediaSource.Container);
```

2022-03-25 14:09 UTC, nyanmisaka commented on Jellyfin.Api/Controllers/DynamicHlsController.cs
> +                var bitStreamArgs = EncodingHelper.GetAudioBitStreamArguments(state, state.Request.SegmentContainer, state.MediaSource.Container, state.TranscodingType);
```suggestion
                var bitStreamArgs = EncodingHelper.GetAudioBitStreamArguments(state, state.Request.SegmentContainer, state.MediaSource.Container);
```

2022-03-25 14:09 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +        public static string GetAudioBitStreamArguments(EncodingJobInfo state, string segmentContainer, string mediaSourceContainer, TranscodingJobType transcodingType)
```suggestion
        public static string GetAudioBitStreamArguments(EncodingJobInfo state, string segmentContainer, string mediaSourceContainer)
```

2022-03-25 14:09 UTC, nyanmisaka commented on MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
> +                    || transcodingType == TranscodingJobType.Hls
```suggestion
                    || string.Equals(mediaSourceContainer, "aac", StringComparison.OrdinalIgnoreCase)
```

2022-03-25 14:13 UTC, nyanmisaka approved these changes

2022-03-25 14:13 UTC, merged