Collection total duration (RunTimeTicks)
jellyfin/jellyfin pull request #7661
Opened 2022-04-25 22:05 UTC by doc-code-hub

The goal is to save a **_reliable value for RunTimeTicks for BoxSets_** ( as I explained better in my issue #7660 ). 

![image](https://user-images.githubusercontent.com/61033694/165181058-900a3e0f-215b-4602-8d1f-a5a32a992349.png)

To achieve this, I made some changes to the `CollectionManager` and created a Task called `CollectionDurationTask`.

## Changes

- ### Add **_UpdateRunTimeTicksToItems_** method in `BoxSet` Entity
```C#
public bool UpdateRunTimeTicksToItems (IList <BaseItem> children);

/// It does nothing but calculate and save the RunTimeTicks of all the children received in the parameter
```
- ### Handle update when adding/removing items from the collection 

In the `CollectionManager`, I created a new method:
```C#
public IList <BaseItem> GetItemsForRunTimeTicksCount (BaseItem item);

/// Based on a BaseItem, it returns the list of items for counting.
/// The list can contain only the received element, or, in case of a series, all its episodes, obtained recursively.
```

I also intervened in the `RemoveFromCollectionAsync` and `AddToCollectionAsync` methods to use the new `GetItemsForRunTimeTicksCount` function and then pass the counting list to the `UpdateRunTimeTicksToItems` method of the BoxSet

- ### Add a Task to update the total duration for the collections 
I thought of a Task for situations like:
- Removing an item from the filesystem
- Update of the RunTimeTicks of a child element

## Issues
fix #7660

---

First time working on my jellyfin fork (and with C#)!
If it needs changes / corrections, I am available

2023-03-25 01:08 UTC, 1337joe requested changes

2023-03-25 01:08 UTC, 1337joe commented on MediaBrowser.Controller/Collections/ICollectionManager.cs
> +        IList<BaseItem> GetItemsForRunTimeTicksCount(BaseItem item);
Interfaces should be as general as possible, can this return an `IEnumerable`?

2023-03-25 02:34 UTC, doc-code-hub commented on MediaBrowser.Controller/Entities/Movies/BoxSet.cs
> +            Console.WriteLine("Update RunTimeTicks To Items: " + children.Count);
Removed

2023-03-29 02:07 UTC, 1337joe approved these changes
I'm not the biggest C# expert we've got, but at this point it looks good to me.

2023-06-27 14:12 UTC, Shadowghost approved these changes

2023-06-29 08:12 UTC, doc-code-hub commented
I solved the conflic from Github, then realized maybe you prefer rebase.

_If this is the case_, please just tell me, and i will force push the rebase i just prepared locally 👍

2023-06-29 09:55 UTC, Shadowghost commented
`MediaBrowser.Controller/Collections/ICollectionManager.cs(74,5): error SA1508: A closing brace should not be preceded by a blank line`

Since the PR is approved, feel free to fix the issue, rebase and force push.

2023-06-29 10:15 UTC, doc-code-hub commented
Thanks Shadownghost for pointing me to the problem!

Fixed the lint issue and now everything runs smoothly in the pipeline 👍

2023-06-29 10:33 UTC, Shadowghost requested changes
Hm I might see another problem with this after dealing with a lot of our ACL code: Collection runtime is not static. It might be different for each user based on to which items within the collection the user has access.

2023-06-29 10:44 UTC, doc-code-hub commented
Mmm... I'm not sure what ACL is, but i see the point... You're right...

I'm thinking, but for now i see that: 
- We can't save the data on DB
- We can't use a task (because of the implicit full-access)

Am i wrong or the only possibile solution is a runtime calculation, based on the logged user's library access?

I'm not seeing other alternatives, right now... Do you?

2024-01-02 21:15 UTC, JPVenson approved these changes

2024-04-30 22:26 UTC, Shadowghost commented
@doc-code-hub yes, I don't think it's possible for us to do it differently. Either we need to on-demand calculate it on server or let the client handle it. Server would be cleaner though.

2024-04-30 23:01 UTC, thornbill commented
Yeah apologies for sending you on what ended up being a wild goose chase... seems it will need to be handled client side 😅

2026-04-16 18:18 UTC, Bond-009 commented
Closing as stale.

2026-04-16 18:18 UTC, closed without merging