Refresh live TV channel image when remapped (issue #7834)
jellyfin/jellyfin pull request #7843
Opened 2022-06-04 16:17 UTC by danielearwicker

**Changes**

In `GetChannelAsync` the `if (!item.HasImage(ImageType.Primary))` check means once a channel has an image, it is never updated. So it continues to have the wrong image even after it has been manually remapped to the correct channel by the user.

To know when the user has done this it seems like we need to store the URL that was fetched to save the local cached image for the channel. If the URL from the EPG is different from this, we should clear the primary image so it is refetched.

That's almost the whole change, except that probably to avoid doing a lot of unnecessary work the existing code in `UpdateImagesAsync` never updates images for any live TV shows or channels. I've left that as it is except now it only applies to shows (of which there are huge numbers) but not channels (of which there are relatively few).

**Issues**

Fixes #7834

2022-11-12 09:52 UTC, jurgenhaas commented
Is there a way I could patch my running Jellyfin installation to give this a try?

2023-06-27 14:10 UTC, Shadowghost commented
@danielearwicker it would be appreciated if you can resolve the conflicts.

2023-12-18 22:20 UTC, Shadowghost approved these changes

2023-12-19 02:22 UTC, 1337joe approved these changes

2023-12-19 09:25 UTC, Bond-009 requested changes

2023-12-19 09:25 UTC, Bond-009 commented on Emby.Server.Implementations/Library/LibraryManager.cs
> +                               parentItem != null &&
```suggestion
                               parentItem is not null &&
```

2024-01-02 21:08 UTC, JPVenson approved these changes

2026-06-08 17:47 UTC, Bond-009 commented
Superseded by #10841

2026-06-08 17:47 UTC, closed without merging