feat: make subtitleeditparser generic
jellyfin/jellyfin pull request #8087
Opened 2022-07-08 17:45 UTC by cvium

**Changes**

**Issues**

2022-07-24 21:21 UTC, crobibero approved these changes

2022-07-30 12:52 UTC, Bond-009 requested changes

2022-07-30 12:52 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +                if (!type.IsSubclassOf(typeof(SubtitleFormat)))
Should we check to make sure it isn't abstract?
```suggestion
                if (!type.IsSubclassOf(typeof(SubtitleFormat)) || type.IsAbstract)
```

2022-07-30 12:52 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            var assembly = Assembly.GetAssembly(typeof(SubtitleFormat));
```suggestion
            var assembly = typeof(SubtitleFormat).Assembly;
```
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getassembly?view=net-7.0#remarks

2022-07-30 12:52 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            if (assembly == null)
Is this case ever hit?

2022-07-30 13:00 UTC, cvium commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            if (assembly == null)
I doubt it, but it's nullable 🤷🏼

2022-07-30 13:05 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            if (assembly == null)
Not anymore ;)

2022-07-30 13:15 UTC, cvium commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            if (assembly == null)
You can remove it then

2022-08-01 16:20 UTC, Bond-009 requested changes

2022-08-01 16:20 UTC, Bond-009 commented on MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
> +            };
```suggestion
```
Isn't this dead code now?

2022-08-01 17:24 UTC, Bond-009 approved these changes

2022-08-01 17:24 UTC, merged