Skip generic shows from duplicate removal actions
jellyfin/jellyfin pull request #8370
Opened 2022-09-07 14:42 UTC by abpei

**Changes**
Workaround for #5856.  Some shows (news, sports, etc.) get published in guides without subkey and are therefore hit by duplicate recording removal, even though the <new> tag is present.  This skips removal of duplicate shows that do not have SubKeys.

**Issues**
Fixes #5856

2022-09-09 11:44 UTC, cvium commented on Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
> +				if (ShowIdSubKey == "0000" )
```suggestion
                // Skip ShowId without SubKey from duplicate removal actions - https://github.com/jellyfin/jellyfin/issues/5856
				if (group.Key.EndsWith("0000")) 
```

2022-09-19 17:13 UTC, cvium approved these changes

2022-09-20 13:04 UTC, Bond-009 requested changes

2022-09-20 13:04 UTC, Bond-009 commented on Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
> +				}
Indented with tabs instead of spaces

2022-10-10 14:13 UTC, crobibero approved these changes

2022-10-10 15:09 UTC, Bond-009 requested changes
It's still indented with tabs instead of spaces

2022-10-10 20:12 UTC, abpei reviewed
I hope it took the update this time. Sorry, I don't do this every day.

2022-10-10 20:25 UTC, Bond-009 approved these changes

2022-10-10 20:25 UTC, merged