Add support for OPUS and fixes for FLAC case issue in HLS
jellyfin/jellyfin pull request #8546
Opened 2022-10-13 10:53 UTC by nyanmisaka

`flac` is supported in Shaka but Safari native HLS only supports `fLaC`.

**Changes**
- Add support for OPUS and fixes for FLAC case issue in HLS

**Web changes**
https://github.com/jellyfin/jellyfin-web/pull/4041

2022-11-22 21:39 UTC, Bond-009 requested changes

2022-11-22 21:39 UTC, Bond-009 commented on Jellyfin.Api/Helpers/DynamicHlsHelper.cs
> +                if (!String.IsNullOrEmpty(flacWaPlaylist))
```suggestion
                if (!string.IsNullOrEmpty(flacWaPlaylist))
```

2022-11-22 21:39 UTC, Bond-009 commented on Jellyfin.Api/Helpers/DynamicHlsHelper.cs
> +                        if (!String.IsNullOrEmpty(flacWaPlaylist))
```suggestion
                        if (!string.IsNullOrEmpty(flacWaPlaylist))
```

2022-11-22 21:39 UTC, Bond-009 commented on Jellyfin.Api/Helpers/DynamicHlsHelper.cs
> +                    if (!String.IsNullOrEmpty(flacWaPlaylist))
```suggestion
                    if (!string.IsNullOrEmpty(flacWaPlaylist))
```

2022-11-27 15:51 UTC, crobibero approved these changes

2022-11-30 20:17 UTC, Bond-009 approved these changes

2022-12-03 15:51 UTC, merged