DVR: Add options to disable NFO and image saving
jellyfin/jellyfin pull request #8775
Opened 2022-11-19 21:20 UTC by SenorSmartyPants

- SaveRecordingNFO and SaveRecordingImages default to true. Maintains current behavior.
- Episode.FillMissingEpisodeNumbersFromPath for live tv so external metadata can be pulled when recording starts.

Fixes #5178

2022-11-27 16:05 UTC, crobibero requested changes

2022-11-27 16:05 UTC, crobibero commented on Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
> +                if (GetConfiguration().SaveRecordingNFO)
Call `GetConfiguration()` once for this function.

2022-11-27 19:17 UTC, crobibero approved these changes

2023-01-03 10:30 UTC, daullmer approved these changes

2023-01-03 11:01 UTC, Bond-009 approved these changes

2023-01-03 11:01 UTC, merged