Remove DvdLib
jellyfin/jellyfin pull request #9068
Opened 2023-01-11 02:43 UTC by barronpm

Based on the investigation done in #5373, the current code for DvdLib is unused, and it doesn't work with Windows paths.

This PR removes the unused/broken code. 

@ferferga, the original PR also removed BDInfo, was that unused as well?

Replaces #5373

2023-01-11 06:09 UTC, Shadowghost approved these changes

2023-01-11 06:09 UTC, Shadowghost commented
Afaik we're using ffmpeg for everything now.

2023-01-11 07:17 UTC, Roardom commented
> Afaik we're using ffmpeg for everything now.

Is this why playback of DVDs has been broken since 10.7.0? (https://github.com/jellyfin/jellyfin/issues/7786)

2023-01-17 17:52 UTC, Bond-009 approved these changes

2023-01-19 14:14 UTC, Shadowghost requested changes
After looking at the playback code and fixing metadata retrival for DVD folders locally I came to the conclusion that playing folders outside of an ISO was never supported for DVDs.

It works for BDs because FFmpeg provides a special protocol handler (`bluray://`) for those folders - which is not the case for DVDs. We'd need to handle VOB selection and concatenation ourself to make playing DVDs from folders work (which we currently do not at all).

While doing so I found another function you can remove (also needs to be removed from the interface):
`MediaBrowser.Encoding.Encoder.MediaEncoder.GetPrimaryPlaylistVobFiles`

2023-01-19 14:14 UTC, Shadowghost commented on MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs
>                          _logger.LogError("No playable vobs found in bluray structure, skipping ffprobe.");
```suggestion
                        _logger.LogError("No playable filesfound in bluray structure, skipping ffprobe.");
```

2023-01-19 23:27 UTC, crobibero approved these changes

2023-01-20 12:29 UTC, merged