Fix API access permissions for LiveTV and downloads
jellyfin/jellyfin pull request #9130
Opened 2023-01-19 23:43 UTC by Shadowghost

**Changes**
* Add policy for accessing LiveTV management endpoints
* Add policy for accessing LiveTV endpoints
* Enforce download permission on download policy

2023-01-20 00:26 UTC, crobibero approved these changes

2023-01-21 22:02 UTC, anthonylavado commented
My testing shows the live tv policies are set and enforced.

2023-01-21 22:59 UTC, cvium requested changes

2023-01-21 22:59 UTC, cvium commented on Jellyfin.Api/Auth/BaseAuthorizationHandler.cs
> +                && !user.HasPermission(PermissionKind.EnableLiveTvAccess))
BaseAuthorizationHandler is becoming way too bloated imo and LiveTv is moving way beyond "Base". I would rather we either retrieve the user in `LiveTvManagementHandler` and `LiveTvAccessHandler` (it's cached by the UserManager) or store the User as a nullable protected property in `BaseAuthorizationHandler`, and then handle the LiveTv check in the respective live tv handlers.

2023-01-22 18:09 UTC, cvium approved these changes
Fix it up in a separate PR

2023-01-22 19:02 UTC, merged