Add "Allowed Tags" to Parental Controls
jellyfin/jellyfin pull request #9139
Opened 2023-01-20 19:44 UTC by Jpuc1143

**Changes**
Parental Controls  can now block all the media that do not have a specified tag, similar to the already existing "Block items with tags" but with a whitelist instead. By default, as long as no tags are configured for the whitelist, no shows will be blocked.

**Issues**
Implements #928

2023-01-22 10:35 UTC, TalEdd commented
Would love this change to be merged to main as soon as possible, it would be a great feature to have

2023-01-29 12:43 UTC, Raik0 commented
Hopefully this can be looked at sooner rather than later

2023-02-05 16:03 UTC, daullmer requested changes

2023-02-05 16:07 UTC, daullmer commented
Adding the setting in the web client would also be nice :)

2023-02-08 16:37 UTC, daullmer commented on MediaBrowser.Controller/Entities/BaseItem.cs
> +            if (user.GetPreference(PreferenceKind.AllowedTags).Any() && !user.GetPreference(PreferenceKind.AllowedTags).Any(i => Tags.Contains(i, StringComparison.OrdinalIgnoreCase)))
Yeah that makes sense. Didn't think that removing that line would leave no way of disabling this feature.

2023-02-08 16:37 UTC, daullmer approved these changes

2023-02-09 22:35 UTC, crobibero commented on MediaBrowser.Controller/Entities/BaseItem.cs
> +            if (user.GetPreference(PreferenceKind.AllowedTags).Any() && !user.GetPreference(PreferenceKind.AllowedTags).Any(i => Tags.Contains(i, StringComparison.OrdinalIgnoreCase)))
Should get the preference once.

```suggestion
            var allowedTagsPreference = user.GetPreference(PreferenceKind.AllowedTags);
            if (allowedTagsPreference.Any() && !allowedTagsPreference.Any(i => Tags.Contains(i, StringComparison.OrdinalIgnoreCase)))
            {
                return false;
            }
```

2023-02-10 00:37 UTC, crobibero approved these changes

2023-02-10 10:50 UTC, Bond-009 approved these changes

2023-02-11 22:52 UTC, merged

2023-02-11 23:50 UTC, Raik0 commented
Merged!!!

2023-06-02 01:18 UTC, 0x11DFE commented
Would also be nice having a way to sort by custom parental rating since sometimes it fails to detect the rating e.g FR-TP (Tout Public) is not available and is sorted as if it was 18+.
Also i had a similar issue where some adult Horror movies were present in the kids profile maybe metadata wasn't able to fetch from DB correctly?

2024-04-17 13:18 UTC, adoreparler commented
Is this working?

I am on version 10.9.0

![Screen Recording 2024-04-17 at 9 14 59 AM](https://github.com/jellyfin/jellyfin/assets/135237656/23a4b449-4eb3-475a-b31b-cd3ae57efe2d)

2024-04-17 13:53 UTC, crobibero commented
@adoreparler Please create an issue for tracking instead of commenting on the PR.