Fix EqualsAny condition check for int and double
jellyfin/jellyfin pull request #9351
Opened 2023-02-18 22:22 UTC by Shadowghost

Currently `EqualsAny` is not implemented for `double` and the implementation for `int` does not work as it should (see #9350)

**Changes**
Split the conditional string value, parse the substrings into a int/double and check if one of them is equal to the current value.

**Issues**
Fixes #9350

2023-02-18 23:42 UTC, Bond-009 requested changes
Use a foreach and our own Split that works on ReadonlySpan<char>

2023-02-19 14:02 UTC, Bond-009 requested changes
Maybe change the other ones in this file too, the default `NumberStyles` should be fine, no need to support currency symbols or hex etc

2023-02-19 14:12 UTC, Bond-009 approved these changes

2023-02-19 15:48 UTC, crobibero approved these changes

2023-02-20 09:27 UTC, merged