chore: ffmpeg version bump & swap to env for file locations
jellyfin/jellyfin pull request #9625
Opened 2023-04-10 16:18 UTC by brettpetch

**Changes**

**Issues**

2023-04-10 16:26 UTC, crobibero commented
As far as I know these dockerfiles aren't actually published anywhere, so changes will also need to be make in the metapackages repo https://github.com/jellyfin/jellyfin-metapackages

2023-04-10 16:32 UTC, brettpetch commented
> As far as I know these dockerfiles aren't actually published anywhere, so changes will also need to be make in the metapackages repo https://github.com/jellyfin/jellyfin-metapackages

Doing this mostly for myself as I build from here to run bleeding edge 😅

2023-05-10 07:10 UTC, Shadowghost approved these changes
I don't mind these changes but it would be nice if we can bump the Intel stuff to the most recent versions before merging.

2023-08-04 10:00 UTC, lonebyte requested changes

2023-08-04 10:00 UTC, lonebyte commented on Dockerfile
> +ENV JELLYFIN_CONFIG_DIR=/config
JELLYFIN_DATA_DIR needs to be set instead, as you want to replace `--datadir`. JELLYFIN_CONFIG_DIR would replace the option `--configdir`.

2023-12-18 20:20 UTC, joshuaboniface approved these changes
I see no issue here though Ghost's feedback should be addressed.

2023-12-27 01:38 UTC, Gauvino commented
> > I see no issue here though Ghost's feedback should be addressed.
> 
> 
> 
> Latest versions should be
> 
> 
> 
> ```dockerfile
> 
> ARG GMMLIB_VERSION=22.3.11
> 
> ARG IGC_VERSION=1.0.15136.4
> 
> ARG NEO_VERSION=23.35.27191.9
> 
> ARG LEVEL_ZERO_VERSION=1.3.27191.9
> 
> ```

Currently reworking this PR with latest version and a little bit more feature, refactoring the build process

2023-12-27 14:17 UTC, brettpetch commented
I think that it might be best to have it always pull the most recent. I don't mind writing that instead of doing args.

2023-12-27 14:18 UTC, Gauvino commented
> I think that it might be best to have it always pull the most recent. I don't mind writing that instead of doing args.

It would be a good idea I think

2023-12-27 14:35 UTC, Shadowghost commented
> I think that it might be best to have it always pull the most recent. I don't mind writing that instead of doing args.

Do not trust the version numbers written in the release description. They are wrong way too often, use the artifacts attached to the compute runtime release if possible.

2024-01-18 01:24 UTC, crobibero commented
closing in favor of https://github.com/jellyfin/jellyfin/pull/10603

2024-01-18 01:24 UTC, closed without merging