Add and enforce playback permission on API
jellyfin/jellyfin pull request #9873
Opened 2023-06-09 08:38 UTC by Shadowghost

**Changes**
* Add auth policy for media playback
* Enforce policy on all playback endpoints

**Issues**
Fixes #9872

2023-06-09 15:56 UTC, Bond-009 approved these changes

2023-06-10 13:01 UTC, crobibero commented
Has this been tested for DLNA playback?

2023-06-10 16:14 UTC, Shadowghost commented
Good point. I did just test it and it does not work due to DLNA not sending an API key at all (I don't think we should do that).
Adding this to the DLNA code should fix it though. I'll look into it.

Since DLNA operates on http sending an api token does expose that token to other devices in the network. The attack surface would therefore be wide than earlier due to the token giving access to restriced endpoints.

Any thoughts on what is preferrable?

2023-06-12 20:05 UTC, PrplHaz4 commented
> 

It sounds unnecessarily risky to have the admin API token exposed anywhere by default.

I think it's "best practice" to always create a DLNA-specific user profile but we don't do a great job of steering people down that path (maybe we should create a default read-only one for them?).

Longer-term both of these could be accomplished by making DLNA opt-in rather than out, and making "DLNA User" a required field - at least then you'd be acknowledging that random devices on your network are impersonating the admin.

2023-06-12 21:11 UTC, Shadowghost commented
We could modify the policy to allow unauthed access on local networks. That should fix the issues.

2023-06-16 08:39 UTC, Shadowghost commented
I changed the policy to only check for the permission if the request is non-LAN. This allows DLNA to keep working and still enforces the permission for external requests.

2023-06-19 13:14 UTC, crobibero requested changes
This change disallows api keys to be used for media playback, is that intentional?

2023-06-23 00:09 UTC, crobibero commented on Jellyfin.Api/Auth/PlaybackPolicy/PlaybackHandler.cs
> +        if (userId.Equals(default) && (ip is null || _networkManager.IsInLocalNetwork(ip)))
I think it's incorrect to succeed the requirement if the userId is empty. Theoretically this only happens if authenticating via api key, but I would like to protect against it

2024-02-03 20:41 UTC, crobibero approved these changes

2024-02-03 21:08 UTC, Shadowghost commented
I need to check if we can secure even more endpoints, now that DLNA is out of the way

2024-03-02 10:37 UTC, nielsvanvelzen requested changes
The Android apps will break with this change and it can only be partially fixed. We can add authorization to the internal player but we will **not** send the access token to external video players, which would effectively break them. Unless we fix this problem first we cannot go forward with this PR.

edit (09-18): While possible it's also not easy to set authorization headers in our internal player. A possible solution to secure the playback endpoint is to have an alternative way to authorize via query parameters that does not grant complete server access like the existing access tokens.

2026-05-21 17:37 UTC, Bond-009 commented
Closing as stale for now

2026-05-21 17:37 UTC, closed without merging

2026-05-22 09:33 UTC, bonswouar commented
I know it feels nice to close "stale" PR/issues, but how can we follow the future progress on this issue then?

Or is it really not planned and the playback permissions settings are useless? Then shouldn't those settings be removed?

2026-05-22 15:33 UTC, Bond-009 commented
> I know it feels nice to close "stale" PR/issues, but how can we follow the future progress on this issue then?

This isn't about feeling 'nice', it's about removing stale and unactionable PRs from our backlog.
To keep track on progress we have multiple issues https://github.com/jellyfin/jellyfin/issues/13984 https://github.com/jellyfin/jellyfin/issues/13986 

> Or is it really not planned and the playback permissions settings are useless? Then shouldn't those settings be removed?

It's planned, see the issues.