Move hardcoded LibraryUpdateDuration to ServerConfiguration.
jellyfin/jellyfin pull request #9894
Opened 2023-06-16 01:51 UTC by fhriley

**Changes**

Move hardcoded LibraryUpdateDuration to ServerConfiguration.

**Issues**

Fixes #9893

2023-06-16 07:40 UTC, Shadowghost approved these changes

2023-06-19 02:08 UTC, crobibero requested changes

2023-06-19 02:08 UTC, crobibero commented on MediaBrowser.Model/Configuration/ServerConfiguration.cs
> +        public int LibraryUpdateDuration { get; set; } = 30;
This is in seconds but the `dueTime` parameter expects milliseconds, making the timer now fire every 30ms.

2023-06-19 20:01 UTC, crobibero reviewed
I would change `Timeout.InfiniteTimeSpan` back to `Timeout.Infinite` as internally the constructor converts to a `uint`

2023-06-20 01:36 UTC, fhriley commented
> I would change `Timeout.InfiniteTimeSpan` back to `Timeout.Infinite` as internally the constructor converts to a `uint`

I can change this, but are you sure? The constructor takes a `TimeSpan` so to use `Timeout.Infinite` we'd have to pass something like `TimeSpan.FromMilliseconds(Timeout.Infinite)`. This codes an assumption that the infinite timespan is in milliseconds. Why not use the constant designed for this and not make the assumption? Or are you saying use the constructor that uses `int`s rather than the `TimeSpan` version?

2023-06-20 01:46 UTC, crobibero commented
>  Or are you saying use the constructor that uses ints rather than the TimeSpan version?

This, what the code was originally doing.

The docs show both work:
> `period`  [TimeSpan](https://learn.microsoft.com/en-us/dotnet/api/system.timespan?view=net-7.0) 
> The time interval between invocations of callback. Specify [InfiniteTimeSpan](https://learn.microsoft.com/en-us/dotnet/api/system.threading.timeout.infinitetimespan?view=net-7.0#system-threading-timeout-infinitetimespan) to disable periodic signaling.

> `period`  [Int32](https://learn.microsoft.com/en-us/dotnet/api/system.int32?view=net-7.0) 
> The time interval between invocations of callback, in milliseconds. Specify [Infinite](https://learn.microsoft.com/en-us/dotnet/api/system.threading.timeout.infinite?view=net-7.0#system-threading-timeout-infinite) to disable periodic signaling.

This is the constructor you moved to, which just takes the `TotalMilliseconds`, so there is no benefit besides requiring extra property access.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs#L848-L862

2023-06-20 01:51 UTC, fhriley commented
I [matched the implementation](https://github.com/jellyfin/jellyfin/blob/c078391aece1b341343d743d7ecfb002ed177f6c/Emby.Server.Implementations/IO/FileRefresher.cs#L79) of `LibraryMonitorDelay`, but fixed the assumption.

2023-06-20 01:55 UTC, fhriley commented
I'll make one more pitch, and then if you still want it changed, I'll change it. The difference is this:

`_configurationManager.Configuration.LibraryUpdateDuration * 1000`

vs

`TimeSpan.FromSeconds(_configurationManager.Configuration.LibraryUpdateDuration)`

The former is not clear what time unit `LibraryUpdateDuration` is in. You only know it's in seconds if you look up the `Timer` constructor and see that it takes milliseconds. OTOH, the latter is very clear just by looking at the code. `LibraryUpdateDuration` is in seconds. Do you still want me to implement the int version?

2023-06-20 01:59 UTC, crobibero commented
🤦 sorry I totally missed that there wasn't a combined constructor. What you have is completely fine and I was just confused at the additional change

2023-06-20 02:00 UTC, crobibero approved these changes

2023-06-20 16:23 UTC, Bond-009 approved these changes

2023-06-20 16:23 UTC, merged