Fix 'replace missing metadata' for music
jellyfin/jellyfin pull request #9985
Opened 2023-07-10 05:34 UTC by GinoGinocchio

**Changes**
The code includes logic that ensures that manually entered data by the user in certain metadata fields is not modified during the process of searching and updating missing metadata

**Issues**
Fixes issue #9760 for music.

2023-07-10 05:35 UTC, cvium commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                audio.Name = string.IsNullOrEmpty(audio.Name.ToString()) ? tags.Title : audio.Name;
Why ToString?

2023-07-10 05:36 UTC, cvium commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                    // audio.Artists = performers;
Remove commented out code

2023-07-10 05:40 UTC, cvium commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                if (!audio.ProviderIds.TryGetValue("MusicBrainzArtist", out var artistValue) || artistValue == null)
Use TryGetProviderId

2023-07-10 05:53 UTC, cvium commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                if (!audio.TryGetProviderId("MusicBrainzArtist", out var artistValue) || string.IsNullOrEmpty(artistValue))
You do not need to check for null nor emptiness. If TryGetProviderId returns true, then it is a valid provider id.

2023-07-10 19:52 UTC, crobibero commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                    audio.AlbumArtists = audio.AlbumArtists != null ? audio.AlbumArtists : albumArtists;
```suggestion
                    audio.Artists ??= performers;
                    audio.AlbumArtists ??= albumArtists;
```

2023-07-10 19:52 UTC, crobibero commented on MediaBrowser.Providers/MediaInfo/AudioFileProber.cs
> +                audio.ParentIndexNumber = audio.ParentIndexNumber != null ? audio.ParentIndexNumber : Convert.ToInt32(tags.Disc);
```suggestion
                audio.Album ??= tags.Album;
                audio.IndexNumber ??= Convert.ToInt32(tags.Track);
                audio.ParentIndexNumber ??= Convert.ToInt32(tags.Disc);
```

2023-07-19 18:44 UTC, IDisposable reviewed
THANK YOU! This is an awesome fix :)

2023-07-29 04:56 UTC, crobibero approved these changes

2023-07-29 05:37 UTC, Shadowghost approved these changes

2023-07-29 12:08 UTC, Bond-009 approved these changes

2023-07-31 17:47 UTC, lonebyte reviewed
Won't this also prevent updating if the metadata should actually be replaced? I think `MetadataRefreshOptions.ReplaceAllMetadata` needs to be evaluated somewhere.

2023-08-10 16:27 UTC, cvium commented
> Won't this also prevent updating if the metadata should actually be replaced? I think `MetadataRefreshOptions.ReplaceAllMetadata` needs to be evaluated somewhere.

I think this is an excellent point

2023-08-11 06:29 UTC, cvium requested changes
See last comment

2023-10-15 13:17 UTC, Shadowghost commented
@GinoGinocchio are you able to look further into this?

2024-02-29 00:35 UTC, crobibero commented
Closing in favor of https://github.com/jellyfin/jellyfin/pull/10691

2024-02-29 00:35 UTC, closed without merging